regs_per_section ={1 : ['OV', 'E', 'GrO', 'IPI', 'Mi', 'EPI', 'Gl'],
2 : ['OV', 'E', 'GrO', 'IPI', 'Mi', 'EPI', 'Gl', 'GrA', 'aci'],
3 : ['OV', 'E', 'GrO', 'IPI', 'Mi', 'EPI', 'Gl', 'GrA', 'aci', 'EPlA', 'MiA', 'dlo', 'AOL', 'AOE', 'unname', 'lo'],
4 : ['OV', 'E', 'GrO', 'IPI', 'Mi', 'EPI', 'Gl', 'GrA', 'aci', 'EPlA', 'MiA', 'dlo', 'AOL', 'AOE', 'lo', 'FrA', 'GlA', 'AOM', 'AOD', 'AOV'],
5 : ['OV', 'E', 'GrO', 'IPI', 'Mi', 'EPI', 'Gl', 'GrA', 'aci', 'AOL', 'AOE', 'lo', 'FrA', 'GlA', 'AOM', 'AOD', 'AOV', 'MO', 'VO', 'LO'],
6 : ['GrO', 'aci', 'AOL', 'unname', 'lo', 'AOM', 'AOD', 'MO', 'VO', 'LO', 'DLO', 'AOVP', 'PrL', 'M2'],
7 : ['aci', 'AOL', 'lo', 'AOM', 'AOD', 'MO', 'VO', 'LO', 'DLO', 'AOVP', 'PrL', 'Fr3', 'M2', 'M1', '2', 'VTT', 'E/OV', 'Pir1'],
8 : ['A32D', 'A32V', 'aca', 'AID', 'AIV', 'AOL', 'AOVP', 'Cl', 'DEn', 'DTr', 'DTT1', 'DTT2', 'DTT3 ', 'DTT4', 'RMS/OV', 'fmi', 'Fr3', 'IEn', 'lo', 'LO', 'lofr', 'M1', 'M2', 'MO', 'mofr', 'Pir1a', 'Pir1b', 'Pir2', 'Pir3', 'rf', 'ri', 'unnamed', 'VO', 'VTT1', 'VTT2', 'VTT3'],
9 : ['A32D', 'A32V', 'aca', 'AID', 'AIV', 'AOP', 'AOVP', 'Cl', 'DEn', 'DP', 'DTr', 'DTT1', 'DTT2', 'DTT3 ', 'DTT4', 'RMS/OV', 'fmi', 'Fr3', 'IEn', 'lo', 'LO', 'lofr', 'M1', 'M2', 'mofr', 'Pir1', 'Pir2', 'Pir3', 'rf', 'ri', 'VO', 'VTT1', 'VTT2', 'VTT3'],
10 : ['A25', 'A32D', 'A32V', 'aca', 'AcbSh', 'AID', 'AIV', 'AOP', 'azac', 'Cl', 'DEn', 'DI', 'DP', 'DTT1', 'DTT2', 'DTT3 ', 'DTT4', 'fmi', 'Fr3', 'ICj', 'IEn', 'lo', 'LO', 'M1', 'M2', 'Nv', 'Pir1', 'Pir2', 'Pir3', 'rf', 'RMS/OV', 'S1J', 'Tu1', 'Tu2', 'Tu3', 'VO', 'unnamed', 'lofr'],
11 : ['lo', 'VO', 'LO', 'PrL', 'Fr3', 'M2', 'M1', '2', 'E/OV', 'AID', 'AIV', 'Cl', 'fmi', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'AOP', 'IL', 'DP', 'Pir1', 'S1J', 'DI', 'Nv', 'azp', 'azac', 'cg', 'AcbSh', 'AcbC', 'VP', '1', 'DTT', 'Tu1'],
12 : ['A24a', 'A24b', 'A25', 'aca', 'AcbC', 'AcbSh', 'AID', 'AIV', 'azac', 'azp', 'cg', 'Cl', 'CPu', 'DEn', 'DI', 'DP', 'DTT1', 'DTT2', 'DTT3 ', 'fmi', 'Fr3', 'GI', 'ICj', 'IEn', 'lo', 'LO', 'lofr', 'M1', 'M2', 'mfb', 'Nv', 'Pir1', 'Pir2', 'Pir3', 'RMS/OV', 'S1J', 'Tu1', 'Tu2', 'Tu3', 'unnamed', 'VP', 'fixed'],
13 : ['E', 'lo', 'LO', 'PrL', 'M2', 'M1', '2', 'E/OV', 'AID', 'AIV', 'Cl', 'fmi', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'IL', 'DP', 'Pir1', 'S1J', 'DI', 'Nv', 'Icj', 'azp', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', '1', 'DTT', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ'],
14 : ['A24a', 'A24b', 'A33', 'aca', 'AcbC', 'AcbSh', 'azac', 'AID', 'AIV', 'azp', 'cc', 'cg', 'Cl', 'CPu', 'DEn', 'DI', 'DP', 'DTT1', 'DTT2', 'E', 'ec', 'gcc', 'GI', 'ICj', 'IEn', 'IG', 'lo', 'LSI', 'LSS', 'LV', 'lofr', 'M1', 'M2', 'Nv', 'Pir1', 'Pir2', 'Pir3', 'S1DZ', 'S1DZO', 'S1FL', 'S1J', 'S1ULp', 'SHi', 'Tu1', 'Tu2', 'Tu3', 'unnamed', 'VP'],
15 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'DP', 'Pir1', 'S1J', 'DI', 'Nv', 'Icj', 'azp', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', '1', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'gcc', 'IG', 'LSI', 'SIDZO', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'ICjM', 'LAcbSh'],
16 : ['A24a', 'A24b', 'A33', 'aca', 'AcbC', 'AcbSh', 'acer', 'AID', 'AIV', 'azp', 'cc', 'cg', 'CPu', 'DCI', 'DEn', 'DI', 'DP', 'E', 'ec', 'gcc', 'GI', 'ICj', 'ICjM', 'IEn', 'IG', 'LAcbSh', 'lo', 'LSD', 'LSI', 'LSS', 'LSV', 'LV', 'M1', 'M2', 'Nv', 'Pir1', 'Pir2', 'Pir3', 'rcc', 'S1DZ', 'S1DZO', 'S1FL', 'S1J', 'S1ULp', 'SHi', 'Tu', 'Tu1', 'Tu2', 'Tu3', 'unnamed', 'VCI', 'VP', 'rf'],
17 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'S1J', 'DI', 'Nv', 'Icj', 'azp', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', '1', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'gcc', 'IG', 'LSI', 'SIDZO', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LAcbSh', 'LSD', 'LSV'],
18 : ['A24a', 'A24b', 'A33', 'aca', 'AcbC', 'AcbSh', 'acer', 'AID', 'AIV', 'azp', 'cc', 'cg', 'CPu', 'DCI', 'DEn', 'DI', 'DP', 'E', 'ec', 'gcc', 'GI', 'ICj', 'ICjM', 'IEn', 'IG', 'LAcbSh', 'lo', 'LSD', 'LSI', 'LSS', 'LSV', 'LV', 'M1', 'M2', 'PDZ', 'Pir1', 'Pir2', 'Pir3', 'rcc', 'S1DZ', 'S1DZO', 'S1FL', 'S1J', 'S1ULp', 'SHi', 'unnamed', 'VCI', 'VDB', 'VP', 'Tu1', 'Tu2', 'Tu3'],
19 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'S1J', 'DI', 'Icj', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', '1', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'gcc', 'IG', 'LSI', 'SIDZO', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'ICjM', 'LAcbSh', 'LSD', 'LSV', 'VDB'],
20 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'S1J', 'DI', 'Icj', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', '1', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'gcc', 'IG', 'LSI', 'SIDZO', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'ICjM', 'LAcbSh', 'LSD', 'LSV', 'VDB', 'MS'],
21 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'S1J', 'DI', 'Icj', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', '1', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'SIDZO', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'ICjM', 'LAcbSh', 'LSD', 'LSV', 'VDB', 'MS', 'cc'],
22 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'S1J', 'DI', 'Icj', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'SIDZO', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'ICjM', 'LAcbSh', 'LSD', 'LSV', 'VDB', 'MS', 'cc', 'PLd'],
23 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'S1J', 'DI', 'Icj', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'SIDZO', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'ICjM', 'LAcbSh', 'LSD', 'LSV', 'VDB', 'MS', 'cc', 'PLd', 'Ld', 'mcer', 'S2'],
24 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'DI', 'Icj', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'ICjM', 'LAcbSh', 'LSD', 'LSV', 'VDB', 'MS', 'cc', 'PLd', 'Ld', 'S2', 'CB', 'HDB', 'SIB'],
25 : ['A24a', 'A24b', 'A33', 'aca', 'acer', 'AcbC', 'AcbSh', 'AID', 'AIV', 'CB', 'cc', 'cg', 'CPu', 'DCI', 'DEn', 'DI', 'E', 'ec', 'GI', 'HDB', 'ICj', 'IEn', 'LAcbSh', 'Ld', 'lo', 'LSD', 'LSI', 'LSS', 'LSV', 'LV', 'M1', 'M2', 'mcer', 'MS', 'PDZ', 'Pir1', 'Pir2', 'Pir3', 'PLd', 'S1DZ', 'S1FL', 'S1ULp', 'S2', 'SHi', 'SIB', 'Tu1', 'Tu2', 'Tu3', 'unnamed', 'VCI', 'VDB', 'VP'],
26 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'DI', 'Icj', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LAcbSh', 'LSD', 'LSV', 'VDB', 'MS', 'cc', 'PLd', 'Ld', 'mcer', 'S2', 'CB', 'HDB', 'SIB', 'STMA'],
27 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'DI', 'Icj', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LSD', 'LSV', 'VDB', 'MS', 'cc', 'PLd', 'Ld', 'mcer', 'S2', 'CB', 'HDB', 'SIB', 'STMA'],
28 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'DI', 'Icj', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LSD', 'LSV', 'VDB', 'MS', 'cc', 'PLd', 'Ld', 'S2', 'CB', 'HDB', 'SIB', 'STMA', 'IPAC', 'LPO', 'Shy', 'VOLT'],
29 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', 'DEn', 'IEn', 'aca', 'Pir1', 'DI', 'Icj', 'cg', 'AcbSh', 'AcbC', 'VP', 'Cpu', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LSD', 'LSV', 'VDB', 'MS', 'cc', 'PLd', 'Ld', 'mcer', 'S2', 'CB', 'HDB', 'SIB', 'STMA', 'IPAC', 'LPO', 'Shy', 'VOLT', 'och', 'MPA', 'MnPO'],
30 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', '4', 'DEn', 'IEn', 'aca', 'Pir1', 'DI', 'Icj', 'cg', 'VP', 'Cpu', '1', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LSD', 'LSV', 'MS', 'cc', 'Ld', 'S2', 'CB', 'HDB', 'SIB', 'STMA', 'IPAC', 'LPO', 'Shy', 'VOLT', 'och', 'MPA', 'MnPO', 'SIHL', 'STLP', 'STLV', 'STMV', 'ZL'],
31 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', '4', 'DEn', 'IEn', 'aca', 'Pir1', 'DI', 'Icj', 'cg', 'VP', 'Cpu', '1', 'GI', 'mfb', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LSD', 'LSV', 'MS', 'cc', 'S2', 'CB', 'HDB', 'SIB', 'STMA', 'IPAC', 'LPO', 'Shy', 'VOLT', 'och', 'MPA', 'MnPO', 'SIHL', 'STLP', 'STLV', 'STMV', 'ZL', 'STLD', 'VMPO'],
32 : ['E', 'lo', 'M2', 'M1', '2', 'AID', 'AIV', 'Cg1', '3', '4', 'DEn', 'IEn', 'aca', 'Pir1', 'DI', 'Icj', 'cg', 'VP', 'Cpu', '1', 'GI', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LSD', 'LSV', 'MS', 'cc', 'mcer', 'S2', 'CB', 'HDB', 'SIB', 'STMA', 'IPAC', 'LPO', 'Shy', 'VOLT', 'och', 'MPA', 'MnPO', 'SIHL', 'STLP', 'STLV', 'STMV', 'ZL', 'STLD', 'VMPO', 'SFi', 'PS', 'mfbb', 'MCPO', 'Fu', 'fi', 'AVPe', 'mfba'],
33 : ['E', 'lo', 'M2', 'M1', '2', 'Cg1', '3', '4', 'DEn', 'IEn', 'aca', 'Pir1', 'DI', 'cg', 'VP', 'Cpu', '1', 'GI', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LSD', 'LSV', 'MS', 'cc', 'S2', 'CB', 'HDB', 'SIB', 'STMA', 'IPAC', 'LPO', 'Shy', 'VOLT', 'och', 'MPA', 'MnPO', 'SIHL', 'STLP', 'STLV', 'STMV', 'STLD', 'VMPO', 'SFi', 'PS', 'mfbb', 'MCPO', 'Fu', 'fi', 'AVPe', 'mfba', 'AIP', 'Al', 'ic', 'SO', 'StA', 'VLPO'],
34 : ['E', 'lo', 'M2', 'M1', '2', 'Cg1', '3', 'DEn', 'IEn', 'Pir1', 'DI', 'cg', 'VP', 'Cpu', '1', 'GI', 'Tu1', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LSD', 'LSV', 'cc', 'S2', 'CB', 'HDB', 'SIB', 'STMA', 'IPAC', 'LPO', 'Shy', 'och', 'MPA', 'MnPO', 'SIHL', 'STLP', 'STLV', 'STMV', 'STLD', 'VMPO', 'SFi', 'PS', 'mfbb', 'MCPO', 'Fu', 'fi', 'AVPe', 'mfba', 'AIP', 'Al', 'ic', 'SO', 'StA', 'VLPO', 'STMAM', 'STMAL', 'STLJ', 'MPOL', 'f', 'CxA1', 'chp', 'acp', 'ac'],
35 : ['E', 'lo', 'M2', 'M1', '2', 'Cg1', '3', 'DEn', 'IEn', 'Pir1', 'DI', 'cg', 'VP', 'Cpu', 'GI', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'SHi', 'LSS', 'DCI', 'VCI', 'LSD', 'LSV', 'cc', 'mcer', 'S2', 'HDB', 'SIB', 'LPO', 'Shy', 'och', 'MPA', 'MnPO', 'SIHL', 'STLP', 'STLV', 'STMV', 'STLD', 'VMPO', 'SFi', 'PS', 'mfbb', 'MCPO', 'Fu', 'fi', 'mfba', 'AIP', 'ic', 'SO', 'StA', 'VLPO', 'STMAM', 'STMAL', 'STLJ', 'MPOL', 'f', 'CxA1', 'chp', 'acp', 'ac', 'Tu', 'AA', 'CST', 'EGP', 'IPACL', 'IPACM', 'Lter', 'MPOM', 'Pe', 'STI', 'TS'],
36 : ['E', 'lo', 'M2', 'M1', '2', 'Cg1', '3', 'DEn', 'IEn', 'Pir1', 'DI', 'cg', 'VP', 'Cpu', 'GI', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'LSI', 'S1ULp', 'LSS', 'DCI', 'VCI', 'LSD', 'LSV', 'cc', 'mcer', 'S2', 'HDB', 'SIB', 'LPO', 'Shy', 'och', 'MPA', 'SIHL', 'STLP', 'STLV', 'STMV', 'VMPO', 'SFi', 'PS', 'mfbb', 'MCPO', 'Fu', 'fi', 'mfba', 'AIP', 'ic', 'SO', 'VLPO', 'STMAM', 'STMAL', 'STLJ', 'MPOL', 'f', 'CxA1', 'chp', 'acp', 'ac', 'AA', 'EGP', 'IPACL', 'IPACM', 'Lter', 'MPOM', 'Pe', 'TS', 'STLI', 'S1BF', 'B'],
37 : ['3V', 'A24aa', 'A24bb', 'A33', 'AA', 'ac', 'AC', 'acer', 'Aco', 'acp', 'AIP', 'B', 'BAC', 'cc', 'cg', 'CPu', 'CxA1', 'CxA2', 'CxA3', 'DA14', 'DCI', 'DEn', 'DI', 'E', 'ec', 'EGP', 'f', 'fi', 'GI', 'HDB', 'ic', 'IEn', 'IPACL', 'IPACM', 'LDB', 'lo', 'LOT', 'LPO', 'LSD', 'LSI', 'LSS', 'LTer', 'LV', 'M1', 'M2', 'mcer', 'mfba', 'mfbb', 'MPA', 'MPOC', 'MPOL', 'MPOM', 'och', 'Pe', 'Pir1', 'Pir2', 'Pir3', 'PS', 'S1BF', 'S1DZ', 'S1FL', 'S1HL', 'S1ULp', 'S2', 'SCh', 'SFi', 'SHy', 'SIB', 'SO', 'st', 'STLI', 'STLP', 'STLV', 'STMAL', 'STMAM', 'TS', 'unnamed', 'VCI', 'VLPO', 'VP'],
38 : ['3V', 'a', 'A24aa', 'A24bb', 'A33', 'AA', 'AC', 'ACo', 'acp', 'AIP', 'B', 'BAC', 'cc', 'cg', 'CPu', 'CxA1', 'CxA2', 'CxA3', 'DCI', 'DEn', 'DI', 'E', 'ec', 'EGP', 'f', 'fi', 'GI', 'HDB', 'ic', 'IEn', 'IPACL', 'IPACM', 'lo', 'LOT1', 'LOT2', 'LPO', 'LSD', 'LSS', 'LV', 'M1', 'M2', 'mcer', 'mch', 'mfba', 'mfbb', 'MPA', 'MPOC', 'MPOL', 'MPOM', 'och', 'PDPO', 'Pe', 'PaAP', 'Pir1', 'Pir2', 'Pir3', 'S1BF', 'S1DZ', 'S1FL', 'S1HL', 'S1ULp', 'S2', 'SCh', 'SFi', 'SFO', 'SIB', 'sm', 'SO', 'sox', 'st', 'StHy', 'STLI', 'STLP', 'STMPI', 'STMPL', 'STMPM', 'TS', 'unnamed', 'VCI', 'VLPO', 'VP', 'LDB'],
39 : ['E', 'lo', 'M2', 'M1', '2', 'Cg1', '3', 'DEn', 'IEn', 'a', 'Pir1', 'DI', 'cg', 'VP', 'Cpu', 'GI', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'S1ULp', 'DCI', 'VCI', 'LSD', 'cc', 'S2', 'HDB', 'SIB', 'LPO', 'och', 'MPA', 'SIHL', 'STLP', 'SFi', 'mfbb', 'MCPO', 'fi', 'mfba', 'AIP', 'ic', 'SO', 'cecece', 'f', 'CxA1', 'chp', 'acp', 'AA', 'EGP', 'IPACL', 'IPACM', 'MPOM', 'Pe', 'TS', 'S1BF', 'B', 'Aco', 'BAC', 'MPOC', 'st', 'StHy', 'vhc', 'STMPM', 'STMPL', 'STMPI', 'sod', 'sm', 'SFO', 'PeAP', 'PDPO', 'LOT1', 'APF', 'cst', 'EAC', 'ESO', 'I\n', 'IVF', 'VLH', 'SChVM', 'SChDL'],
40 : ['lo', 'M2', 'M1', '2', 'Cg1', '3', 'DEn', 'Pir1', 'DI', 'cg', 'VP', 'Cpu', 'GI', 'mfb', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'S1ULp', 'DCI', 'VCI', 'LSD', 'cc', 'S2', 'HDB', 'SIB', 'LPO', 'och', 'MPA', 'SIHL', 'STLP', 'SFi', 'MCPO', 'fi', 'AIP', 'ic', 'SO', 'MPOL', 'f', 'CxA1', 'chp', 'acp', 'AA', 'EGP', 'IPACL', 'IPACM', 'MPOM', 'Pe', 'TS', 'S1BF', 'B', 'Aco', 'BAC', 'st', 'StHy', 'vhc', 'STMPM', 'STMPL', 'STMPI', 'sod', 'sm', 'SFO', 'mch', 'LOT1', 'APF', 'EAC', 'ESO', 'I\n', 'IVF', 'VLH', 'Ven', 'SChVM', 'SChDL', 'PVA', 'PaAP', 'LA', 'df'],
41 : ['lo', 'M2', 'M1', '2', 'Cg1', '3', 'DEn', 'a', 'Pir1', 'DI', 'cg', 'VP', 'Cpu', 'GI', 'mfb', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'S1ULp', 'DCI', 'VCI', 'LSD', 'cc', 'S2', 'HDB', 'LPO', 'MPA', 'SIHL', 'SFi', 'MCPO', 'fi', 'AIP', 'ic', 'SO', 'f', 'CxA1', 'chp', 'acp', 'AA', 'EGP', 'IPACL', 'IPACM', 'MPOM', 'Pe', 'TS', 'S1BF', 'B', 'Aco', 'st', 'StHy', 'vhc', 'STMPM', 'STMPL', 'STMPI', 'sod', 'sm', 'SFO', 'mch', 'LOT1', 'APF', 'cst', 'EAC', 'ESO', 'IVF', 'VLH', 'Ven', 'SChVM', 'SChDL', 'PVA', 'PaAP', 'LA', 'df', 'AHA', 'opt', 'PT', 'SPa'],
42 : ['lo', 'M2', 'M1', '2', 'Cg1', '3', 'DEn', 'Pir1', 'DI', 'cg', 'VP', 'Cpu', 'GI', 'mfb', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'S1ULp', 'DCI', 'VCI', 'cc', 'S2', 'HDB', 'LPO', 'MPA', 'SIHL', 'SFi', 'MCPO', 'fi', 'AIP', 'ic', 'SO', 'f', 'CxA1', 'acp', 'AA', 'EGP', 'IPACL', 'IPACM', 'MPOM', 'Pe', 'TS', 'S1BF', 'B', 'Aco', 'st', 'StHy', 'vhc', 'STMPM', 'STMPL', 'STMPI', 'sod', 'sm', 'SFO', 'LOT1', 'cst', 'EAC', 'ESO', 'I\n', 'IVF', 'VLH', 'Ven', 'PVA', 'PaAP', 'LA', 'df', 'AHA', 'opt', 'PT', 'SPa', 'Rt', 'RtSt', 'SM', 'STMP', 'Re', 'RCh', 'MeAD', 'D3V', 'AV', 'AM'],
43 : ['lo', 'M2', 'M1', '2', 'Cg1', '3', 'DEn', 'a', 'Pir1', 'DI', 'cg', 'Cpu', 'GI', 'mfb', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'S1ULp', 'DCI', 'VCI', 'cc', 'S2', 'HDB', 'MPA', 'SIHL', 'MCPO', 'fi', 'AIP', 'ic', 'SO', 'f', 'CxA1', 'chp', 'acp', 'AA', 'EGP', 'IPACL', 'IPACM', 'Pe', 'TS', 'S1BF', 'B', 'Aco', 'st', 'vhc', 'STMPM', 'STMPL', 'sod', 'sm', 'SFO', 'LOT1', 'cst', 'EAC', 'ESO', 'I\n', 'VLH', 'Ven', 'PVA', 'PaAP', 'LA', 'df', 'AHA', 'opt', 'PT', 'SPa', 'Rt', 'RtSt', 'SM', 'Re', 'RCh', 'MeAD', 'D3V', 'AM', 'AD', 'ANS', 'AVMD', 'AVVL', 'BMA', 'EAM', 'MPO', 'PLH', 'VRe'],
44 : ['lo', 'M2', 'M1', '2', 'Cg1', '3', 'DEn', 'a', 'Pir1', 'DI', 'cg', 'Cpu', 'GI', 'mfb', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'S1ULp', 'DCI', 'VCI', 'cc', 'S2', 'HDB', 'IPAC', 'MPA', 'SIHL', 'MCPO', 'fi', 'AIP', 'ic', 'SO', 'f', 'CxA1', 'chp', 'AA', 'EGP', 'Pe', 'TS', 'S1BF', 'Aco', 'st', 'vhc', 'STMPM', 'STMPL', 'sod', 'sm', 'SFO', 'LOT1', 'cst', 'EAC', 'ESO', 'I\n', 'VLH', 'Ven', 'PVA', 'PaAP', 'LA', 'df', 'AHA', 'opt', 'PT', 'SPa', 'Rt', 'RtSt', 'Re', 'RCh', 'MeAD', 'D3V', 'AM', 'AD', 'ANS', 'AVMD', 'AVVL', 'BMA', 'EAM', 'PLH', 'VRe', 'PC', 'IAD', 'CM'],
45 : ['M2', 'M1', '2', 'Cg1', '3', 'DEn', 'a', 'Pir1', 'DI', 'cg', 'Cpu', 'GI', 'mfb', 'LV', 'SIFL', 'SIDZ', 'Cg2', 'ec', 'IG', 'S1ULp', 'DCI', 'VCI', 'cc', 'S2', 'HDB', 'IPAC', 'SIHL', 'MCPO', 'fi', 'AIP', 'ic', 'SO', 'f', 'CxA1', 'chp', 'AA', 'EGP', 'Pe', 'TS', 'S1BF', 'Aco', 'st', 'vhc', 'STMPM', 'sod', 'sm', 'SFO', 'LOT1', 'cst', 'EAC', 'ESO', 'I\n', 'VLH', 'Ven', 'PVA', 'LA', 'df', 'AHA', 'opt', 'PT', 'SPa', 'Rt', 'RtSt', 'SM', 'Re', 'RCh', 'MeAD', 'D3V', 'AM', 'AD', 'ANS', 'AVMD', 'AVVL', 'BMA', 'EAM', 'PLH', 'VRe', 'PC', 'IAD', 'CM', 'AMV', 'CeM', 'Cir', 'JPLH', 'PaMM', 'PaMP', 'PaV', 'RChL', 'STSL', 'STSM', 'Xi'],
46 : ['A24aa', 'A24bb', 'AA', 'ACo', 'AD', 'AHC', 'AIP', 'AM', 'AMV', 'ANS', 'aot', 'ASt', 'AVDM', 'AVVL', 'BAOT', 'BLA', 'BMA', 'cc', 'CeC', 'CeM', 'cg', 'CM', 'CPu', 'cst', 'CxA1', 'CxA2', 'CxA3', 'D3V', 'DCI', 'DEn', 'df', 'DI', 'EAC', 'EAM', 'EA', 'ec', 'EGP', 'f', 'fi', 'GI', 'HDB', 'I\n', 'IAD', 'ic', 'IGP', 'JPLH', 'LV', 'LDB', 'M1', 'M2', 'MeAD', 'MoDG', 'opt', 'PaMM', 'PaMP', 'PaV', 'PaXi', 'PC', 'Pe', 'Pir1', 'Pir2', 'Pir3', 'PLH', 'PT', 'PVA', 'RCh', 'RChL', 'Re', 'Rt', 'RtSt', 'S1BF', 'S1DZ', 'S1HL', 'S1Sh', 'S1ULp', 'S2', 'SFO', 'sm', 'SO', 'sox', 'SPa', 'st', 'STSL', 'STSM', 'TuLH', 'unnamed', 'VA', 'VCI', 'VEn', 'vhc', 'VLH', 'VRe', 'Xi'],
47 : ['M2', 'M1', '2', '3', 'DEn', 'a', 'Pir1', 'DI', 'cg', 'Cpu', 'GI', 'mfb', 'LV', 'SIDZ', 'ec', 'IG', 'S1ULp', 'DCI', 'VCI', 'cc', 'S2', 'SIHL', 'fi', 'AIP', 'ic', 'SO', 'f', 'CxA1', 'chp', 'AA', 'EGP', 'Pe', 'S1BF', 'B', 'Aco', 'st', 'vhc', 'sod', 'sm', 'SFO', 'cst', 'I\n', 'Ven', 'PVA', 'df', 'opt', 'PT', 'SPa', 'Rt', 'RtSt', 'Re', 'RCh', 'MeAD', 'D3V', 'AM', 'AD', 'ANS', 'AVMD', 'AVVL', 'BMA', 'PLH', 'VRe', 'PC', 'IAD', 'CM', 'AMV', 'CeM', 'JPLH', 'PaMP', 'PaV', 'RChL', 'Xi', 'VA', 'TuLH', 'S1Sh', 'PaXi', 'MoDG', 'CeC', 'BLA', 'BAOT', 'Ast', 'AHC', 'AHP', 'alv', 'Arc', 'CA3', 'EA', 'GrDG', 'IAM', 'MD', 'MeAV', 'mt', 'ns', 'Or', 'PaDC', 'PaLM', 'RSD', 'RSGc', 'VA/VL', 'vlh', 'VMHA', 'VMHSh'],
48 : ['M2', 'M1', '2', '3', 'DEn', 'a', 'Pir1', 'DI', 'cg', 'Cpu', 'GI', 'mfb', 'LV', 'SIDZ', 'ec', 'IG', 'S1ULp', 'DCI', 'VCI', 'cc', 'S2', 'SIHL', 'fi', 'AIP', 'ic', 'SO', 'f', 'chp', 'AA', 'EGP', 'Pe', 'S1BF', 'B', 'Aco', 'st', 'vhc', 'sod', 'sm', 'SFO', 'cst', 'Ven', 'PVA', 'df', 'opt', 'PT', 'SPa', 'Rt', 'RtSt', 'Re', 'MeAD', 'D3V', 'AM', 'AD', 'ANS', 'AVMD', 'AVVL', 'BMA', 'PLH', 'VRe', 'PC', 'IAD', 'CM', 'AMV', 'CeM', 'JPLH', 'PaMP', 'PaV', 'RChL', 'Xi', 'VA', 'TuLH', 'S1Sh', 'PaXi', 'MoDG', 'CeC', 'BLA', 'BAOT', 'Ast', 'AHC', 'AHP', 'alv', 'Arc', 'CA3', 'EA', 'GrDG', 'IAM', 'MD', 'MeAV', 'mt', 'ns', 'Or', 'PaDC', 'PaLM', 'RSD', 'RSGc', 'vlh', 'VMHSh', 'VM', 'VMH', 'VL', 'Rh', 'Py', 'MHb', 'ME', 'LDVL'],
49 : ['DEn', 'M1', 'M2', 'Pir2', 'Pir3', 'Pir1', 'DI', 'CPu', 'GI', 'cc', 'ec', 'LV', 'S1DZ', 'S1ULp', 'DCI', 'VCI', 'S2', 'unnamed', '3V', 'AIP', 'EGP', 'f', 'ic', 'Pe', 'S1BF', 'S1HL', 'st', 'a', 'ACo', 'fi', 'sm', 'sox', 'AD', 'AHC', 'AM', 'AMV', 'ANS', 'ASt', 'AVDM', 'AVVL', 'BAOT', 'BLA', 'BMA', 'CeC', 'CeM', 'CM', 'cst', 'D3V', 'df', 'MeAD', 'MoDG', 'opt', 'PaMP', 'PaV', 'PaXi', 'PC', 'PLH', 'PT', 'PVA', 'RChL', 'Re', 'Rt', 'RtSt', 'S1Sh', 'VA', 'VRe', 'A29c', 'A30', 'AHP', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CA2', 'CA3', 'CeL', 'dhc', 'EP', 'GrDG', 'IM', 'LDVL', 'MD', 'MeAV', 'MEE', 'MHb', 'mt', 'PaDC', 'Rh', 'SLu', 'SOR', 'vlh', 'VM', 'VMHSh', 'ZIR', 'MEI', 'Sub', 'VMH', 'cg'],
50 : ['M2', 'M1', '2', '3', 'DEn', 'Pir1', 'DI', 'cg', 'Cpu', 'GI', 'mfb', 'LV', 'SIDZ', 'ec', 'IG', 'S1ULp', 'cc', 'S2', 'SIHL', 'fi', 'AIP', 'ic', 'f', 'chp', 'EGP', 'Pe', 'S1BF', 'Aco', 'st', 'sod', 'sm', 'cst', 'Ven', 'PVA', 'df', 'opt', 'PT', 'SPa', 'Rt', 'RtSt', 'Re', 'MeAD', 'D3V', 'AM', 'AD', 'ANS', 'AVMD', 'AVVL', 'BMA', 'PLH', 'VRe', 'PC', 'CM', 'CeM', 'PaMP', 'RChL', 'VA', 'TuLH', 'S1Sh', 'PaXi', 'MoDG', 'CeC', 'BLA', 'BAOT', 'Ast', 'AHC', 'AHP', 'alv', 'CA3', 'GrDG', 'IAM', 'MD', 'MeAV', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'vlh', 'VMHSh', 'VM', 'VL', 'Rh', 'Py', 'MHb', 'LDVL', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CeL', 'dhc', 'IGP', 'IM', 'MEE', 'MEI', 'Rad', 'Slu', 'SOR', 'Sub', 'ZIR', 'VMHC', 'VMHDM', 'VMHVL', 'Stg', 'PaPo', 'MDL', 'LDDM', 'LaDL', 'A13'],
51 : ['M2', 'M1', '2', '3', 'DEn', 'Pir1', 'DI', 'cg', 'Cpu', 'GI', 'mfb', 'LV', 'SIDZ', 'ec', 'IG', 'S1ULp', 'cc', 'S2', 'SIHL', 'fi', 'AIP', 'ic', 'f', 'chp', 'EGP', 'Pe', 'S1BF', 'Aco', 'st', 'sod', 'sm', 'cst', 'Ven', 'df', 'opt', 'PT', 'Rt', 'RtSt', 'Re', 'MeAD', 'D3V', 'AM', 'AD', 'AVMD', 'AVVL', 'BMA', 'PLH', 'VRe', 'PC', 'CM', 'CeM', 'RChL', 'Xi', 'VA', 'TuLH', 'S1Sh', 'PaXi', 'MoDG', 'CeC', 'BLA', 'BAOT', 'AHP', 'alv', 'CA3', 'GrDG', 'IAM', 'MeAV', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'vlh', 'VMHSh', 'VM', 'VL', 'Rh', 'Py', 'MHb', 'LDVL', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CeL', 'dhc', 'IGP', 'IM', 'MEE', 'MEI', 'Rad', 'Slu', 'SOR', 'Sub', 'ZIR', 'VMHC', 'VMHDM', 'VMHVL', 'Stg', 'PaPo', 'MDL', 'LDDM', 'LaDL', 'A13', 'CL', 'MDM', 'PeFLH', 'PLCo', 'PoDG', 'PTe', 'PV', 'VPL'],
52 : ['M2', 'M1', '2', '3', '4', 'DEn', 'a', 'Pir1', 'DI', 'cg', 'Cpu', 'GI', 'mfb', 'LV', 'SIDZ', 'ec', 'IG', 'S1ULp', 'cc', 'S2', 'SIHL', 'fi', 'AIP', 'ic', 'f', 'chp', 'EGP', 'Pe', 'S1BF', 'Aco', 'st', 'sod', 'sm', 'cst', 'I\n', 'Ven', 'df', 'opt', 'Rt', 'RtSt', 'Re', 'MeAD', 'D3V', 'AM', 'AD', 'AVMD', 'BMA', 'PLH', 'VRe', 'PC', 'CM', 'CeM', 'RChL', 'Xi', 'VA', 'TuLH', 'S1Sh', 'PaXi', 'MoDG', 'CeC', 'BLA', 'AHP', 'alv', 'CA3', 'GrDG', 'MeAV', 'mt', 'ns', 'Or', 'RSD', 'vlh', 'VMHSh', 'VM', 'VL', 'Rh', 'Py', 'MHb', 'LDVL', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CeL', 'dhc', 'IGP', 'MEE', 'MEI', 'Rad', 'Slu', 'SOR', 'ZIR', 'VMHC', 'VMHDM', 'VMHVL', 'Stg', 'PaPo', 'MDL', 'LDDM', 'LaDL', 'A13', 'CL', 'MDM', 'PeFLH', 'PLCo', 'PoDG', 'PTe', 'PV', 'VPL', 'CA1', 'SubV', 'SubD', 'STIA', 'LHb', 'DMD', 'DA', 'CA2', '6b', '6a', '5b', '5a', '5'],
53 : ['DEn', 'M1', 'M2', 'Pir2', 'Pir3', 'Pir1', 'DI', 'CPu', 'GI', 'cc', 'LV', 'S1DZ', 'S1ULp', 'S2', 'unnamed', '3V', 'AIP', 'EGP', 'f', 'ic', 'Pe', 'S1BF', 'st', 'a', 'ACo', 'fi', 'sm', 'sox', 'AM', 'AVDM', 'BLA', 'BMA', 'CeC', 'CeM', 'CM', 'cst', 'D3V', 'df', 'MeAD', 'MoDG', 'opt', 'PaXi', 'PLH', 'RChL', 'Re', 'Rt', 'VEn', 'VRe', 'Xi', 'A29c', 'A30', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CA2', 'CA3', 'CeL', 'EP', 'GrDG', 'LDVL', 'MeAV', 'MEE', 'MHb', 'mt', 'Rh', 'SLu', 'SOR', 'vlh', 'VM', 'VMHSh', 'ZIR', 'Ang', 'BLP', 'CA1', 'DA', 'DA13', 'DMD', 'I\n', 'IMD', 'LaDL', 'LDDM', 'LHb', 'MDL', 'MDM', 'MePD', 'PeFLH', 'PLCo', 'PoDG', 'PV', 'S1Tr', 'STIA', 'SubD', 'SubV', 'VL', 'VMHC', 'VMHDM', 'VMHVL', 'VPL', 'MEI'],
54 : ['M2', 'M1', '2', '3', 'DEn', 'a', 'Pir1', 'DI', 'cg', 'Cpu', '1', 'GI', 'mfb', 'LV', 'SIDZ', 'ec', 'IG', 'S1ULp', 'cc', 'S2', 'fi', 'AIP', 'ic', 'f', 'chp', 'EGP', 'Pe', 'S1BF', 'Aco', 'st', 'sod', 'sm', 'cst', 'I\n', 'Ven', 'df', 'opt', 'Rt', 'Re', 'MeAD', 'D3V', 'BMA', 'PLH', 'VRe', 'PC', 'CM', 'CeM', 'RChL', 'TuLH', 'PaXi', 'MoDG', 'CeC', 'BLA', 'Ast', 'alv', 'CA3', 'GrDG', 'MeAV', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'vlh', 'VMHSh', 'VM', 'VL', 'Rh', 'Py', 'MHb', 'LDVL', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CeL', 'dhc', 'IGP', 'MEE', 'MEI', 'Rad', 'Slu', 'SOR', 'VMHC', 'VMHDM', 'VMHVL', 'MDL', 'LDDM', 'LaDL', 'A13', 'CL', 'MDM', 'PeFLH', 'PoDG', 'PTe', 'PV', 'VPL', 'CA1', 'SubV', 'SubD', 'STIA', 'LHb', 'DMD', 'DA', 'CA2', 'AngT', 'BLP', 'IMD', 'MePD', 'S1Tr', 'ZI', 'VMP', 'Po', 'PLCo1', 'MCLH', 'Lmol', 'IMG', 'BMP'],
55 : ['M2', 'M1', '2', '3', 'DEn', 'a', 'Pir1', 'DI', 'cg', 'Cpu', '1', 'GI', 'mfb', 'LV', 'SIDZ', 'ec', 'IG', 'S1ULp', 'cc', 'S2', 'fi', 'AIP', 'ic', 'f', 'chp', 'EGP', 'Pe', 'S1BF', 'Aco', 'st', 'sod', 'sm', 'cst', 'I\n', 'Ven', 'df', 'opt', 'Rt', 'Re', 'MeAD', 'D3V', 'BMA', 'PLH', 'VRe', 'PC', 'CM', 'CeM', 'TuLH', 'PaXi', 'MoDG', 'CeC', 'BLA', 'Ast', 'alv', 'CA3', 'GrDG', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'vlh', 'VMHSh', 'VM', 'VL', 'Rh', 'Py', 'MHb', 'LDVL', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CeL', 'dhc', 'IGP', 'MEE', 'MEI', 'Rad', 'Slu', 'VMHC', 'VMHDM', 'VMHVL', 'MDL', 'LDDM', 'LaDL', 'A13', 'CL', 'MDM', 'PeFLH', 'PoDG', 'PTe', 'PV', 'VPL', 'CA1', 'SubV', 'SubD', 'STIA', 'LHb', 'DMD', 'DA', 'CA2', 'AngT', 'BLP', 'IMD', 'MePD', 'S1Tr', 'ZI', 'VMP', 'Po', 'PLCo1', 'MCLH', 'Lmol', 'IMG', 'BMP', 'dcw', 'LaVL', 'LaVM', 'MDC', 'MePV', 'ml', 'Mtu', 'PeF'],
56 : ['DEn', 'M1', 'M2', 'Pir2', 'Pir3', 'Pir1', 'CPu', 'GI', 'cc', 'LV', 'S1DZ', 'S1ULp', 'S2', 'unnamed', 'AIP', 'EGP', 'f', 'ic', 'Pe', 'S1BF', 'st', 'a', 'fi', 'sm', 'sox', 'BLA', 'BMA', 'CeC', 'CeM', 'CM', 'cst', 'D3V', 'df', 'MoDG', 'opt', 'PaXi', 'PLH', 'Re', 'Rt', 'VEn', 'VRe', 'A29c', 'A30', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CA2', 'CA3', 'CeL', 'EP', 'GrDG', 'LDVL', 'MEE', 'MHb', 'mt', 'Rh', 'SLu', 'vlh', 'VM', 'VMHSh', 'BLP', 'CA1', 'DA', 'DA13', 'DMD', 'IMD', 'LaDL', 'LDDM', 'LHb', 'MDL', 'MDM', 'MePD', 'PeFLH', 'PoDG', 'PV', 'S1Tr', 'STIA', 'SubD', 'SubV', 'VL', 'VMHC', 'VMHDM', 'VMHVL', 'VPL', 'BMP', 'IMG', 'LaVL', 'LaVM', 'LMol', 'MCLH', 'MDC', 'MePV', 'ml', 'MTu', 'PeF', 'PLCo1', 'PLCo2', 'PLCo3', 'PMCo', 'Po', 'SubI', 'VPM', 'ZID', 'ZIV'],
57 : ['M2', 'M1', '2', '3', 'DEn', 'a', 'Pir1', 'DI', 'cg', 'Cpu', 'GI', 'mfb', 'LV', 'SIDZ', 'ec', 'IG', 'S1ULp', 'cc', 'S2', 'fi', 'AIP', 'ic', 'f', 'chp', 'EGP', 'Pe', 'S1BF', 'st', 'sod', 'sm', 'cst', 'I\n', 'Ven', 'df', 'opt', 'Rt', 'Re', 'D3V', 'PLH', 'VRe', 'PC', 'CM', 'CeM', 'TuLH', 'MoDG', 'CeC', 'BLA', 'Ast', 'alv', 'CA3', 'GrDG', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'VMHSh', 'VM', 'VL', 'Rh', 'Py', 'MHb', 'LDVL', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CeL', 'dhc', 'MEE', 'MEI', 'Rad', 'Slu', 'Sub', 'VMHC', 'VMHDM', 'VMHVL', 'MDL', 'LDDM', 'LaDL', 'A13', 'CL', 'MDM', 'PeFLH', 'PoDG', 'PTe', 'PV', 'VPL', 'CA1', 'STIA', 'DMD', 'DA', 'CA2', 'BLP', 'IMD', 'MePD', 'S1Tr', 'VMP', 'Po', 'PLCo1', 'MCLH', 'Lmol', 'BMP', 'dcw', 'LaVL', 'LaVM', 'MDC', 'MePV', 'ml', 'Mtu', 'PeF', 'ZIV', 'ZID', 'SubI', 'PMCo', 'FC', 'LHbL', 'LHbM', 'PHD', 'RAPir'],
58 : ['DEn', 'M1', 'M2', 'Pir2', 'Pir3', 'Pir1', 'CPu', 'cc', 'LV', 'S1DZ', 'S1ULp', 'S2', 'unnamed', 'EGP', 'f', 'ic', 'Pe', 'S1BF', 'st', 'a', 'fi', 'sm', 'sox', 'BLA', 'CeC', 'CM', 'cst', 'D3V', 'df', 'MoDG', 'opt', 'PLH', 'Re', 'Rt', 'VRe', 'A29c', 'A30', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CA2', 'CA3', 'CeL', 'GrDG', 'LDVL', 'MEE', 'MHb', 'mt', 'Rh', 'SLu', 'VM', 'VMHSh', 'BLP', 'CA1', 'DA', 'DMD', 'IMD', 'LaDL', 'LDDM', 'MDL', 'MDM', 'MePD', 'PeFLH', 'PoDG', 'S1Tr', 'STIA', 'VL', 'VMHC', 'VMHDM', 'VMHVL', 'VPL', 'BMP', 'LaVL', 'LaVM', 'LMol', 'MCLH', 'MDC', 'MePV', 'ml', 'MTu', 'PeF', 'PLCo1', 'PLCo2', 'PLCo3', 'PMCo', 'Po', 'SubI', 'VPM', 'ZID', 'AuD', 'DA11', 'DMC', 'Ect', 'FC', 'fr', 'LHbL', 'LHbM', 'MEI', 'p3', 'PHD', 'PRh', 'PTe', 'PVP', 'RAPir', 'Sub', 'Te'],
59 : ['M2', 'M1', '2', '3', 'DEn', 'a', 'Pir1', 'cg', 'Cpu', '1', 'mfb', 'LV', 'SIDZ', 'ec', 'IG', 'S1ULp', 'cc', 'S2', 'fi', 'ic', 'f', 'chp', 'EGP', 'Pe', 'S1BF', 'st', 'sod', 'sm', 'cst', 'I\n', 'df', 'opt', 'Rt', 'Re', 'D3V', 'PLH', 'VRe', 'PC', 'CM', 'TuLH', 'MoDG', 'CeC', 'BLA', 'Ast', 'alv', 'CA3', 'GrDG', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'VMHSh', 'VM', 'VL', 'Rh', 'Py', 'MHb', 'LDVL', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CeL', 'dhc', 'MEE', 'MEI', 'Rad', 'Slu', 'Sub', 'VMHC', 'VMHDM', 'VMHVL', 'MDL', 'LDDM', 'LaDL', 'CL', 'MDM', 'PeFLH', 'PoDG', 'PTe', 'VPL', 'CA1', 'STIA', 'DMD', 'DA', 'CA2', 'BLP', 'IMD', 'MePD', 'S1Tr', 'VMP', 'Po', 'PLCo1', 'MCLH', 'Lmol', 'BMP', 'dcw', 'LaVL', 'LaVM', 'MDC', 'MePV', 'ml', 'Mtu', 'PeF', 'ZIV', 'ZID', 'SubI', 'PMCo', 'FC', 'LHbL', 'LHbM', 'PHD', 'RAPir', 'Te', 'PVP', 'PRh', 'fr', 'Ect', 'DMC', 'AuD', 'A11', 'AHiAL', 'DMV', 'LEnt', 'LPMR', 'LPtA'],
60 : ['DEn', 'M2', 'Pir2', 'Pir3', 'Pir1', 'CPu', 'cc', 'LV', 'S1DZ', 'S2', 'unnamed', '3V', 'f', 'ic', 'Pe', 'S1BF', 'st', 'a', 'fi', 'sm', 'sox', 'BLA', 'CeC', 'CM', 'cst', 'D3V', 'df', 'MoDG', 'opt', 'PLH', 'Re', 'Rt', 'VRe', 'A29c', 'A30', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'CA2', 'CA3', 'CeL', 'GrDG', 'LDVL', 'MEE', 'MHb', 'mt', 'Rh', 'SLu', 'VM', 'VMHSh', 'BLP', 'CA1', 'DMD', 'IMD', 'LaDL', 'MDL', 'MDM', 'MePD', 'PeFLH', 'PoDG', 'S1Tr', 'STIA', 'VPL', 'BMP', 'LaVL', 'LaVM', 'LMol', 'MDC', 'MePV', 'MTu', 'PeF', 'PLCo1', 'PLCo2', 'PLCo3', 'PMCo', 'Po', 'SubI', 'VPM', 'ZID', 'ZIV', 'AuD', 'DA11', 'DMC', 'Ect', 'FC', 'fr', 'LHbL', 'LHbM', 'MEI', 'p3', 'PRh', 'PVP', 'RAPir', 'Sub', 'Te', 'AHiAL', 'Au1', 'AuV', 'CL', 'DLG', 'DLEnt', 'DMV', 'eml', 'LPMR', 'LPtA', 'MPtA', 'ns', 'OPC', 'STh', 'VMH'],
61 : ['2', '3', 'DEn', 'a', 'Pir1', 'cg', 'Cpu', '1', 'mfb', 'LV', 'SIDZ', 'ec', 'IG', 'cc', 'S2', 'fi', 'ic', 'f', 'chp', 'Pe', 'S1BF', 'st', 'sod', 'sm', 'cst', 'df', 'opt', 'Rt', 'Re', 'D3V', 'PLH', 'VRe', 'PC', 'CM', 'TuLH', 'MoDG', 'CeC', 'BLA', 'Ast', 'alv', 'CA3', 'GrDG', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'VMHSh', 'VM', 'VMH', 'Py', 'MHb', 'LDVL', 'ArcD', 'ArcL', 'ArcM', 'BLV', 'dhc', 'MEE', 'MEI', 'Rad', 'Slu', 'MDL', 'LaDL', 'CL', 'MDM', 'PeFLH', 'PoDG', 'VPL', 'CA1', 'STIA', 'DMD', 'CA2', 'BLP', 'IMD', 'MePD', 'S1Tr', 'VMP', 'Po', 'PLCo1', 'Lmol', 'BMP', 'dcw', 'LaVL', 'LaVM', 'MDC', 'MePV', 'ml', 'Mtu', 'PeF', 'ZIV', 'ZID', 'PMCo', 'FC', 'LHbL', 'LHbM', 'PHD', 'RAPir', 'Te', 'PVP', 'PRh', 'fr', 'Ect', 'DMC', 'AuD', 'A11', 'AHiAL', 'DMV', 'LEnt', 'LPMR', 'LPtA', 'VMH', 'VLG\n', 'OPC', 'MPtA', 'eml', 'DLG', 'AuV', 'Au1', 'PH', 'scp'],
62 : ['DEn', 'Pir2', 'Pir3', 'Pir1', 'CPu', 'cc', 'LV', 'S2', 'unnamed', '3V', 'f', 'ic', 'Pe', 'S1BF', 'st', 'a', 'sm', 'sox', 'CM', 'cst', 'D3V', 'df', 'MoDG', 'opt', 'PLH', 'Re', 'Rt', 'A29c', 'A30', 'CA2', 'CA3', 'GrDG', 'MHb', 'mt', 'SLu', 'VM', 'BLP', 'CA1', 'DMD', 'IMD', 'LaDL', 'MDL', 'MDM', 'MePD', 'PeFLH', 'PoDG', 'STIA', 'VPL', 'BMP', 'LaVM', 'LMol', 'MePV', 'MTu', 'PeF', 'PLCo1', 'PLCo2', 'PLCo3', 'PMCo', 'Po', 'VPM', 'ZID', 'ZIV', 'AuD', 'DA11', 'DMC', 'Ect', 'FC', 'fr', 'LHbL', 'LHbM', 'PRh', 'PVP', 'RAPir', 'Te', 'AHiAL', 'Au1', 'AuV', 'DLG', 'DLEnt', 'eml', 'LPMR', 'LPtA', 'MPtA', 'ns', 'OPC', 'STh', 'ArcLP', 'ArcMP', 'InfS', 'LPLR', 'PH', 'PrG', 'scp', 'VPPC'],
63 : ['2', '3', 'DEn', 'a', 'Pir1', 'cg', 'Cpu', '1', 'mfb', 'LV', 'ec', 'IG', 'cc', 'S2', 'fi', 'ic', 'f', 'chp', 'S1BF', 'st', 'sod', 'sm', 'cst', 'df', 'opt', 'Rt', 'D3V', 'PLH', 'PC', 'CM', 'MoDG', 'alv', 'CA3', 'GrDG', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'VM', 'Py', 'MHb', 'dhc', 'Rad', 'Slu', 'MDL', 'LaDL', 'CL', 'MDM', 'PeFLH', 'PoDG', 'VPL', 'CA1', 'STIA', 'CA2', 'BLP', 'IMD', 'MePD', 'VMP', 'Po', 'PLCo1', 'Lmol', 'BMP', 'dcw', 'LaVM', 'MePV', 'ml', 'PeF', 'ZIV', 'ZID', 'PMCo', 'FC', 'LHbL', 'LHbM', 'PHD', 'RAPir', 'Te', 'PVP', 'PRh', 'fr', 'Ect', 'AuD', 'A11', 'AHiAL', 'LEnt', 'LPMR', 'LPtA', 'VLG\n', 'OPC', 'MPtA', 'eml', 'DLG', 'AuV', 'Au1', 'PH', 'scp', 'VPPC', 'LPLR', 'InfS', 'ArcMP', 'ArcLP', 'DM', 'DTM', 'PMV', 'RRe'],
64 : ['2', '3', 'DEn', 'Pir1', 'cg', 'Cpu', '1', 'mfb', 'LV', 'ec', 'IG', 'cc', 'S2', 'fi', 'ic', 'f', 'chp', 'S1BF', 'st', 'sod', 'sm', 'cst', 'df', 'opt', 'Rt', 'D3V', 'PLH', 'PC', 'CM', 'MoDG', 'alv', 'CA3', 'GrDG', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'VM', 'Py', 'MHb', 'dhc', 'Rad', 'Slu', 'MDL', 'LaDL', 'CL', 'MDM', 'PeFLH', 'PoDG', 'VPL', 'CA1', 'CA2', 'BLP', 'IMD', 'VMP', 'Po', 'PLCo1', 'Lmol', 'BMP', 'dcw', 'LaVM', 'ml', 'ZIV', 'ZID', 'PMCo', 'FC', 'LHbL', 'LHbM', 'PHD', 'Te', 'PVP', 'PRh', 'fr', 'Ect', 'AuD', 'A11', 'AHiAL', 'LEnt', 'LPMR', 'LPtA', 'OPC', 'MPtA', 'eml', 'DLG', 'AuV', 'Au1', 'PH', 'scp', 'VPPC', 'LPLR', 'InfS', 'ArcMP', 'ArcLP', 'DM', 'DTM', 'PMV', 'RRe', 'VTM', 'VLG1 ', 'PSTh', 'PF', 'Apir'],
65 : ['2', '3', 'DEn', 'a', 'Pir1', 'cg', 'Cpu', '1', 'mfb', 'LV', 'ec', 'IG', 'cc', 'S2', 'fi', 'ic', 'f', 'chp', 'S1BF', 'st', 'sod', 'sm', 'df', 'opt', 'Rt', 'D3V', 'PLH', 'PC', 'CM', 'MoDG', 'alv', 'CA3', 'GrDG', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'Py', 'MHb', 'dhc', 'Rad', 'Slu', 'MDL', 'LaDL', 'CL', 'MDM', 'PeFLH', 'PoDG', 'VPL', 'CA1', 'CA2', 'BLP', 'VMP', 'Po', 'PLCo1', 'Lmol', 'BMP', 'dcw', 'LaVM', 'ml', 'ZIV', 'ZID', 'PMCo', 'FC', 'LHbL', 'LHbM', 'Te', 'PVP', 'PRh', 'fr', 'Ect', 'AuD', 'A11', 'AHiAL', 'LEnt', 'LPMR', 'LPtA', 'VLG\n', 'OPC', 'MPtA', 'eml', 'DLG', 'AuV', 'Au1', 'PH', 'scp', 'VPPC', 'LPLR', 'InfS', 'ArcMP', 'ArcLP', 'DTM', 'PMV', 'RRe', 'VTM', 'PSTh', 'PF', 'Apir', 'IGL', 'IMA', 'iml', 'PoMn', 'PR', 'PtPD', 'S1', 'SPF', '}}}FAD      '],
66 : ['2', '3', 'DEn', 'a', 'Pir1', 'cg', 'Cpu', '1', 'mfb', 'LV', 'ec', 'IG', 'cc', 'fi', 'ic', 'f', 'chp', 'S1BF', 'st', 'sod', 'sm', 'df', 'opt', 'Rt', 'D3V', 'PLH', 'PC', 'CM', 'MoDG', 'alv', 'CA3', 'GrDG', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'Py', 'MHb', 'dhc', 'Rad', 'Slu', 'MDL', 'LaDL', 'CL', 'MDM', 'PoDG', 'VPL', 'CA1', 'CA2', 'BLP', 'VMP', 'Po', 'PLCo1', 'Lmol', 'BMP', 'dcw', 'LaVM', 'ml', 'ZIV', 'ZID', 'PMCo', 'FC', 'LHbL', 'LHbM', 'Te', 'PVP', 'PRh', 'fr', 'Ect', 'AuD', 'A11', 'AHiAL', 'LEnt', 'LPMR', 'LPtA', 'VLG\n', 'OPC', 'MPtA', 'DLG', 'AuV', 'Au1', 'PH', 'scp', 'VPPC', 'LPLR', 'ArcMP', 'ArcLP', 'PMV', 'RRe', 'VTM', 'PSTh', 'PF', 'Apir', 'IGL', 'IMA', 'PoMn', 'PR', 'PtPD', 'S1', 'SPF', 'MRe', 'Gem', 'DG'],
67 : ['2', '3', 'DEn', 'a', 'Pir1', 'cg', '1', 'mfb', 'LV', 'IG', 'cc', 'fi', 'ic', 'f', 'chp', 'S1BF', 'st', 'sod', 'sm', 'df', 'opt', 'Rt', 'D3V', 'PLH', 'MoDG', 'alv', 'CA3', 'GrDG', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'Py', 'MHb', 'dhc', 'Rad', 'Slu', 'LaDL', 'CL', 'PoDG', 'VPL', 'CA2', 'BLP', 'VMP', 'Po', 'PLCo1', 'Lmol', 'BMP', 'dcw', 'LaVM', 'ml', 'ZIV', 'ZID', 'PMCo', 'FC', 'LHbL', 'LHbM', 'PVP', 'PRh', 'fr', 'Ect', 'AuD', 'A11', 'LEnt', 'LPMR', 'LPtA', 'VLG\n', 'MPtA', 'DLG', 'AuV', 'Au1', 'PH', 'scp', 'VPPC', 'LPLR', 'ArcMP', 'ArcLP', 'RRe', 'VTM', 'PF', 'Apir', 'IGL', 'IMA', 'PR', 'PtPD', 'S1', 'SPF', 'MRe', 'Gem', 'AHiPL', 'AHiPM', 'F', 'hbc', 'PrC', 'SubG', 'SuML'],
68 : ['2', '3', 'DEn', 'a', 'Pir1', 'cg', '1', 'mfb', 'LV', 'IG', 'cc', 'fi', 'ic', 'f', 'chp', 'S1BF', 'sod', 'sm', 'df', 'opt', 'D3V', 'PLH', 'MoDG', 'alv', 'CA3', 'GrDG', 'mt', 'ns', 'Or', 'RSD', 'RSGc', 'Py', 'MHb', 'dhc', 'Rad', 'Slu', 'CL', 'PLCo', 'PoDG', 'VPL', 'CA1', 'CA2', 'BLP', 'VMP', 'Po', 'Lmol', 'dcw', 'ml', 'ZIV', 'ZID', 'PMCo', 'FC', 'LHbL', 'LHbM', 'PRh', 'fr', 'Ect', 'AuD', 'A11', 'LEnt', 'LPMR', 'VLG\n', 'DLG', 'AuV', 'Au1', 'PH', 'scp', 'VPPC', 'LPLR', 'ArcMP', 'ArcLP', 'VTM', 'PF', 'Apir', 'IGL', 'IMA', 'PR', 'PtPD', 'S1', 'SPF', 'MRe', 'Gem', 'AHiPL', 'AHiPM', 'F', 'hbc', 'PrC', 'SubG', 'SuML', 'V2MM', 'V2ML', 'SuMM', 'SPFPC', 'PVG', 'PtPR', 'MnM', 'MM', 'ML', 'LM', 'La'],
69 : ['2', '3', 'DEn', 'a', 'Pir1', 'cg', '1', 'mfb', 'LV', 'IG', 'cc', 'f', 'chp', 'S1BF', 'sod', 'sm', 'opt', 'D3V', 'PLH', 'MoDG', 'alv', 'CA3', 'GrDG', 'ns', 'Or', 'RSD', 'RSGc', 'Py', 'MHb', 'dhc', 'Rad', 'Slu', 'CL', 'PLCo', 'PoDG', 'VPL', 'CA1', 'LHb', 'CA2', '      ', 'BLP', 'VMP', 'Po', 'Lmol', 'dcw', 'ml', 'ZIV', 'ZID', 'PMCo', 'FC', 'PRh', 'fr', 'Ect', 'AuD', 'A11', 'LEnt', 'LPMR', 'VLG\n', 'DLG', 'AuV', 'Au1', 'PH', 'scp', 'VPPC', 'LPLR', 'ArcMP', 'VTM', 'PF', 'Apir', 'IGL', 'IMA', 'PR', 'PtPD', 'S1', 'MRe', 'Gem', 'AHiPL', 'AHiPM', 'F', 'hbc', 'PrC', 'SubG', 'SuML', 'V2MM', 'V2ML', 'SuMM', 'SPFPC', 'PVG', 'PtPR', 'MnM', 'MM', 'ML', 'LM', 'APTD', 'bsc\n', 'mtg', 'pm', 'RI', 'SNR', 'sumd', 'Vli'],
70 : ['2', '3', 'DEn', 'a', 'Pir1', 'cg', '1', 'mfb', 'LV', 'IG', 'cc', 'ic', 'f', 'chp', 'sod', 'opt', 'D3V', 'PLH', 'MoDG', 'alv', 'CA3', 'GrDG', 'ns', 'Or', 'RSD', 'RSGc', 'Py', 'MHb', 'dhc', 'Rad', 'Slu', 'PLCo', 'PoDG', 'VPL', 'CA1', 'CA2', 'BLP', 'VMP', 'Po', 'Lmol', 'dcw', 'ml', 'PMCo', 'FC', 'PRh', 'fr', 'Ect', 'AuD', 'A11', 'LEnt', 'LPMR', 'VLG\n', 'DLG', 'AuV', 'Au1', 'scp', 'LPLR', 'VTM', 'PF', 'Apir', 'IGL', 'IMA', 'PR', 'PtPD', 'S1', 'MRe', 'Gem', 'AHiPL', 'AHiPM', 'F', 'hbc', 'PrC', 'SubG', 'SuML', 'V2MM', 'V2ML', 'SuMM', 'SPFPC', 'PVG', 'PtPR', 'MnM', 'MM', 'ML', 'LM', 'APTD', 'bsc\n', 'mtg', 'RI', 'SNR', 'sumd', 'Vli', 'ZIC', 'V1', 'SCO', 'Sc', 'Pli', 'PHA', 'OPT', 'MPT', 'mp', 'LPMC', 'Eth', 'APTV'],
71 : ['2', '3', 'a', 'Pir1', 'cg', '1', 'LV', 'IG', 'cc', 'ic', 'f', 'chp', 'sod', 'opt', 'D3V', 'PLH', 'MoDG', 'alv', 'CA3', 'GrDG', 'ns', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'Slu', 'PLCo', 'PoDG', 'CA1', 'CA2', 'BLP', 'VMP', 'Po', 'Lmol', 'dcw', 'ml', 'PMCo', 'FC', 'PRh', 'fr', 'Ect', 'AuD', 'LEnt', 'LPMR', 'VLG\n', 'DLG', 'AuV', 'Au1', 'scp', 'LPLR', 'VTM', 'Apir', 'IGL', 'IMA', 'PR', 'PtPD', 'S1', 'AHiPM', 'F', 'hbc', 'PrC', 'SubG', 'SuML', 'V2MM', 'V2ML', 'SuMM', 'SPFPC', 'PVG', 'PtPR', 'MM', 'ML', 'LM', 'APTD', 'bsc\n', 'mtg', 'RI', 'SNR', 'sumd', 'Vli', 'ZIC', 'V1', 'SCO', 'Sc', 'Pli', 'PHA', 'OPT', 'MPT', 'mp', 'LPMC', 'Eth', 'APTV', 'LPLC', 'LT', 'Lth', 'MCPC', 'PBP', 'pc', 'SNCD', 'SNL', 'TeA', 'VS'],
72 : ['2', '3', 'a', 'Pir1', 'cg', '1', 'LV', 'IG', 'cc', 'f', 'chp', 'opt', 'D3V', 'MoDG', 'alv', 'CA3', 'GrDG', 'ns', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'Slu', 'PLCo', 'PoDG', 'CA1', 'CA2', 'BLP', 'VMP', 'Po', 'Lmol', 'dcw', 'ml', 'PMCo', 'FC', 'PRh', 'fr', 'Ect', 'AuD', 'LEnt', 'LPMR', 'DLG', 'AuV', 'Au1', 'scp', 'VTM', '759aaa', 'Apir', 'IGL', 'IMA', 'PR', 'PtPD', 'AHiPM', 'hbc', 'PrC', 'SubG', 'SuML', 'V2MM', 'V2ML', 'SuMM', 'SPFPC', 'PVG', 'PtPR', 'MM', 'ML', 'LM', 'APTD', 'bsc\n', 'mtg', 'RI', 'SNR', 'sumd', 'Vli', 'ZIC', 'V1', 'SCO', 'Sc', 'Pli', 'OPT', 'MPT', 'mp', 'LPMC', 'Eth', 'APTV', 'LPLC', 'LT', 'Lth', 'MCPC', 'PBP', 'pc', 'SNCD', 'SNL', 'TeA', 'VS', 'VTAR', 'RPF', 'REth', 'OT', 'Dk'],
73 : ['Pir2', 'Pir3', 'Pir1', 'cc', 'LV', 'unnamed', '3V', 'a', 'D3V', 'MoDG', 'opt', 'A29c', 'A30', 'CA2', 'CA3', 'dhc', 'GrDG', 'SLu', 'CA1', 'PLCo', 'PoDG', 'LMol', 'ml', 'PMCo', 'Po', 'VPM', 'AuD', 'Ect', 'FC', 'fr', 'PRh', 'Au1', 'AuV', 'DLG', 'DLEnt', 'PrG', 'scp', 'AHiPM', 'APir', 'APTD', 'cg', 'cp', 'Dk', 'Eth', 'IGL', 'IMA', 'LM', 'LPLC', 'LPMC', 'LT', 'Lth', 'MCPC', 'MGD', 'MGV', 'ML', 'MM', 'mp', 'MPT', 'mtg', 'MZMG', 'OPT', 'PBP', 'pc', 'PCom', 'PLi', 'PPA', 'PtPD', 'PtPR', 'REn', 'REth', 'RMM', 'RPF', 'SCO', 'SNCD', 'SNL', 'SNR', 'SPFPC', 'str', 'Subiculum', 'TeA', 'V1', 'V2L', 'V2ML', 'V2MM', 'VLi', 'VS', 'VTAR', 'VTM', 'ZIC', 'APTV', 'alv'],
74 : ['2', '3', 'a', 'Pir1', 'cg', '1', 'LV', 'IG', 'cc', 'chp', 'opt', 'D3V', 'MoDG', 'alv', 'CA3', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'Slu', 'PLCo', 'PoDG', 'CA1', 'CA2', 'Po', 'Lmol', 'dcw', 'ml', 'PMCo', 'FC', 'PRh', 'fr', 'Ect', 'AuD', 'LEnt', 'VLG\n', 'DLG', 'AuV', 'Au1', 'scp', 'VTM', 'Apir', 'IGL', 'IMA', 'PR', 'PtPD', 'AHiPM', 'V2MM', 'V2ML', 'SPFPC', 'PtPR', 'ML', 'APTD', 'bsc\n', 'mtg', 'SNR', 'Vli', 'ZIC', 'V1', 'SCO', 'Pli', 'OPT', 'MPT', 'mp', 'LPMC', 'APTV', 'LPLC', 'LT', 'Lth', 'MCPC', 'PBP', 'pc', 'SNCD', 'SNL', 'TeA', 'VS', 'VTAR', 'RPF', 'REth', 'OT', 'Dk', 'MGD', 'MGV', 'MZMG', 'Pcom', 'PIL', 'SuM', 'Rli', 'PoT', 'PAG', 'MT', 'MGM', 'DS', 'BL', 'Aq'],
75 : ['cc', 'unnamed', 'D3V', 'MoDG', 'opt', 'A29c', 'A30', 'CA2', 'CA3', 'dhc', 'GrDG', 'SLu', 'CA1', 'PoDG', 'LMol', 'ml', 'PMCo', 'Po', 'AuD', 'Ect', 'FC', 'fr', 'PRh', 'Au1', 'AuV', 'DLG', 'DLEnt', 'PrG', 'scp', 'AHiPM', 'APir', 'APTD', 'cp', 'Dk', 'IGL', 'IMA', 'LPLC', 'LPMC', 'LT', 'Lth', 'MCPC', 'MGD', 'MGV', 'ML', 'mp', 'MPT', 'mtg', 'MZMG', 'PBP', 'pc', 'PCom', 'PLi', 'PPA', 'PtPD', 'PtPR', 'REth', 'SCO', 'SNCD', 'SNL', 'SNR', 'SPFPC', 'TeA', 'V1', 'V2L', 'V2ML', 'V2MM', 'VS', 'VTAR', 'ZIC', 'APTV', 'Aq', 'DS', 'IF', 'InC', 'InCSh', 'ipf', 'MA3', 'MGM', 'MT', 'p1', 'p1Rt', 'PIL', 'pIPAG', 'PP', 'PrEW', 'RLi', 'SG', 'TG', 'alv'],
76 : ['unnamed', 'a', 'D3V', 'MoDG', 'opt', 'A29c', 'A30', 'CA2', 'CA3', 'dhc', 'GrDG', 'SLu', 'CA1', 'PoDG', 'LMol', 'ml', 'PMCo', 'Po', 'AuD', 'Ect', 'fr', 'PRh', 'Au1', 'AuV', 'DLG', 'DLEnt', 'PrG', 'AHiPM', 'APir', 'APTD', 'cp', 'Dk', 'IMA', 'LPLC', 'LPMC', 'LT', 'Lth', 'MCPC', 'MGD', 'MGV', 'ML', 'mp', 'MPT', 'mtg', 'MZMG', 'PBP', 'pc', 'PCom', 'PLi', 'PPA', 'PtPR', 'REth', 'SNCD', 'SNL', 'SNR', 'SPFPC', 'TeA', 'V1', 'V2L', 'V2ML', 'V2MM', 'VS', 'ZIC', 'DS', 'IF', 'InC', 'InCSh', 'MA3', 'MGM', 'MT', 'p1', 'p1Rt', 'PIL', 'pIPAG', 'PP', 'PrEW', 'RLi', 'SG', 'TG', 'InWh', 'PaC', 'PN', 'RPC'],
77 : ['a', 'cg', 'opt', 'MoDG', 'alv', 'CA3', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'Slu', 'PoDG', 'CA1', 'CA2', 'Po', 'Lmol', 'dcw', 'ml', 'PMCo', 'FC', 'PRh', 'fr', 'Ect', 'AuD', 'LEnt', 'VLG\n', 'DLG', 'AuV', 'Au1', 'scp', 'Apir', 'IMA', 'PtPD', 'AHiPM', 'V2MM', 'V2ML', 'PtPR', 'ML', 'APTD', 'bsc\n', 'mtg', 'SNR', 'V1', 'Pli', 'OPT', 'MPT', 'mp', 'LPMC', 'APTV', 'LPLC', 'LT', 'MCPC', 'PBP', 'pc', 'SNCD', 'SNL', 'TeA', 'VS', 'REth', 'OT', 'Dk', 'EW', 'MGD', 'MGV', 'MZMG', 'Pcom', 'PIL', 'Rli', 'PoT', 'MT', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'InCSh', 'MA3', 'PP', 'PPT', 'SG', 'RPC', 'PN', 'PaC', 'InWh', 'csc', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'PIPAG', 'SuG', 'Zo'],
78 : ['a', 'cg', 'opt', 'MoDG', 'alv', 'CA3', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'Slu', 'PoDG', 'CA1', 'Po', 'Lmol', 'dcw', 'ml', 'PMCo', 'PRh', 'fr', 'Ect', 'AuD', 'LEnt', 'DLG', 'AuV', 'Au1', 'scp', 'Apir', 'IMA', 'PtPD', 'AHiPM', 'V2MM', 'V2ML', 'PtPR', 'ML', 'APTD', 'bsc\n', 'mtg', 'SNR', 'V1', 'Pli', 'OPT', 'mp', 'LPMC', 'APTV', 'LPLC', 'LT', 'MCPC', 'PBP', 'pc', 'SNCD', 'SNL', 'TeA', 'VS', 'OT', 'Dk', 'EW', 'MGD', 'MGV', 'MZMG', 'Pcom', 'PIL', 'Rli', 'PoT', 'MT', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'InCSh', 'MA3', 'PP', 'PPT', 'SG', 'RPC', 'PN', 'PaC', 'InWh', 'csc', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'PIPAG', 'SuG', 'Zo', 'vtgd', 'RMC', 'mlf', 'EpP', 'DpG'],
79 : ['a', 'cg', 'opt', 'MoDG', 'alv', 'CA3', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'Slu', 'PoDG', 'CA1', 'Po', 'Lmol', 'dcw', 'ml', 'PMCo', 'PRh', 'fr', 'Ect', 'AuD', 'LEnt', 'AuV', 'Au1', 'scp', 'Apir', 'PtPD', 'AHiPM', 'V2MM', 'V2ML', 'PtPR', 'APTD', 'bsc\n', 'mtg', 'SNR', 'V1', 'Pli', 'mp', 'LPMC', 'APTV', 'PBP', 'pc', 'SNCD', 'SNL', 'TeA', 'VS', 'OT', 'Dk', 'EW', 'MGD', 'MGV', 'MZMG', 'PIL', 'Rli', 'PoT', 'MT', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'InCSh', 'MA3', 'PP', 'PPT', 'SG', 'RPC', 'PN', 'PaC', 'InWh', 'csc', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'PIPAG', 'SuG', 'Zo', 'vtgd', 'RMC', 'mlf', 'EpP', 'DpG', '3n', 'DpWh', 'IP', 'PaR', 'PIF', 'RSGa', 'V2L'],
80 : ['cg', 'MoDG', 'alv', 'CA3', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'Slu', 'PoDG', 'CA1', 'Po', 'Lmol', 'dcw', 'ml', 'PMCo', 'PRh', 'fr', 'Ect', 'AuD', 'LEnt', 'AuV', 'Au1', 'scp', 'Apir', 'PtPD', 'AHiPM', 'V2MM', 'V2ML', 'PtPR', 'bsc\n', 'mtg', 'SNR', 'V1', 'Pli', 'mp', 'LPMC', 'PBP', 'SNCD', 'SNL', 'TeA', 'VS', 'OT', 'Dk', 'EW', 'MGD', 'MGV', 'MZMG', 'PIL', 'Rli', 'PoT', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'InCSh', 'PP', 'SG', 'RPC', 'PN', 'PaC', 'InWh', 'csc', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'PIPAG', 'SuG', 'Zo', 'vtgd', 'RMC', 'mlf', 'EpP', 'DpG', '3n', 'DpWh', 'PaR', 'PIF', 'RSGa', 'V2L', 'IPR', 'IPL', 'IPC', 'APT'],
81 : ['a', 'cg', 'MoDG', 'alv', 'CA3', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'Slu', 'PoDG', 'CA1', 'Po', 'Lmol', 'dcw', 'ml', 'PRh', 'Ect', 'AuD', 'LEnt', 'AuV', 'Au1', 'scp', 'Apir', 'AHiPM', 'V2MM', 'V2ML', 'bsc\n', 'mtg', 'SNR', 'V1', 'Pli', 'mp', 'LPMC', 'PBP', 'SNCD', 'SNL', 'TeA', 'VS', 'OT', 'Dk', 'EW', 'MGD', 'MGV', 'MZMG', 'PIL', 'Rli', 'PoT', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'InCSh', 'MA3', 'PP', 'SG', 'RPC', 'PN', 'InWh', 'csc', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'vtgd', 'RMC', 'mlf', 'DpG', '3n', 'DpWh', 'PaR', 'PIF', 'RSGa', 'V2L', 'IPR', 'IPL', 'IPC', 'APT', 'DpMe', 'PtPC', 'SNCM', 'SNCV'],
82 : ['cg', 'MoDG', 'alv', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'Slu', 'PoDG', 'CA1', 'Lmol', 'dcw', 'ml', 'PRh', 'Ect', 'AuD', 'LEnt', 'AuV', 'Au1', 'scp', 'Apir', 'V2MM', 'V2ML', 'bsc\n', 'mtg', 'SNR', 'mp', 'PBP', 'SNCD', 'SNL', 'TeA', 'VS', 'Dk', 'EW', 'MGD', 'MGV', 'MZMG', 'PIL', 'Rli', 'PoT', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'InCSh', 'MA3', 'PP', 'SG', 'RPC', 'PN', 'InWh', 'csc', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'vtgd', 'RMC', 'mlf', 'DpG', '3n', 'DpWh', 'PaR', 'PIF', 'RSGa', 'V2L', 'IPR', 'IPL', 'IPC', 'APT', 'DpMe', 'PtPC', 'SNCM', 'SNCV', 'V1M', 'V1BB', 'Ment', 'Elm', 'DLPAG', 'bic'],
83 : ['a', 'cg', 'MoDG', 'alv', 'CA3', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'PoDG', 'CA1', 'Lmol', 'dcw', 'ml', 'PRh', 'Ect', 'AuD', 'LEnt', 'AuV', 'Au1', 'Apir', 'V2MM', 'V2ML', 'mtg', 'SNR', 'mp', 'PBP', 'SNCD', 'SNL', 'TeA', 'VS', 'EW', 'MGD', 'MGV', 'MZMG', 'PIL', 'Rli', 'PoT', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'InCSh', 'MA3', 'SG', 'RPC', 'PN', 'InWh', 'csc', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'vtgd', 'RMC', 'mlf', 'DpG', 'DpWh', 'PaR', 'PIF', 'RSGa', 'V2L', 'IPR', 'IPL', 'IPC', 'DpMe', 'PtPC', 'SNCM', 'SNCV', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'DT', 'Post', 'Su3', 'SubB', 'tth'],
84 : ['a', 'MoDG', 'alv', 'CA3', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'PoDG', 'CA1', 'Lmol', 'dcw', 'ml', 'PRh', 'Ect', 'AuD', 'LEnt', 'AuV', 'Au1', 'Apir', 'V2MM', 'V2ML', 'bsc\n', 'SNR', 'PBP', 'SNCD', 'SNL', 'TeA', 'VS', 'EW', 'MGD', 'MGV', 'MZMG', 'PIL', 'Rli', 'PoT', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'InCSh', 'SG', 'RPC', 'PN', 'InWh', 'csc', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'vtgd', 'RMC', 'mlf', 'DpG', 'DpWh', 'PaR', 'PIF', 'RSGa', 'V2L', 'IPR', 'IPL', 'IPC', 'DpMe', 'PtPC', 'SNCM', 'SNCV', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'DT', 'Post', 'Su3', 'SubB', 'tth', 'Su3C', 'IPDM', 'dtgd', '3PC'],
85 : ['a', 'MoDG', 'alv', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'PoDG', 'CA1', 'Lmol', 'dcw', 'ml', 'PRh', 'Ect', 'AuD', 'AuV', 'Au1', 'Apir', 'V2MM', 'V2ML', 'bsc\n', 'SNR', 'PBP', 'SNCD', 'SNL', 'TeA', 'VS', 'EW', 'MGD', 'MGV', 'MZMG', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'SG', 'RPC', 'PN', 'InWh', 'csc', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'vtgd', 'RMC', 'mlf', 'DpG', 'DpWh', 'PaR', 'PIF', 'RSGa', 'V2L', 'IPR', 'IPL', 'IPC', 'DpMe', 'SNCM', 'SNCV', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'DT', 'Post', 'Su3', 'SubB', 'tth', 'Su3C', 'IPDM', 'dtgd', '3PC', '3N', 'bas', 'CLi', 'DIEnt', 'IPDL', 'pcer', 'ts', 'VIEnt'],
86 : ['MoDG', 'alv', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'PoDG', 'CA1', 'Lmol', 'dcw', 'ml', 'PRh', 'Ect', 'AuD', 'AuV', 'Au1', 'Apir', 'V2MM', 'V2ML', 'bsc\n', 'SNR', 'PBP', 'SNCD', 'SNL', 'TeA', 'VS', 'EW', 'MGD', 'MGV', 'MZMG', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'RPC', 'PN', 'InWh', 'csc', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'vtgd', 'RMC', 'mlf', 'DpG', 'DpWh', 'PaR', 'PIF', 'RSGa', 'V2L', 'IPR', 'IPL', 'IPC', 'DpMe', 'SNCM', 'SNCV', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'DT', 'Post', 'Su3', 'SubB', 'tth', 'Su3C', 'IPDM', 'dtgd', '3PC', '3N', 'bas', 'CLi', 'DIEnt', 'IPDL', 'pcer', 'ts', 'VIEnt', 'scpd', 'rs', 'RRF', 'me5', 'Me5'],
87 : ['a', 'MoDG', 'alv', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'PoDG', 'CA1', 'Lmol', 'dcw', 'ml', 'PRh', 'Ect', 'AuD', 'AuV', 'Au1', 'scp', 'Apir', 'V2MM', 'V2ML', 'SNR', 'PBP', 'SNCD', 'SNL', 'TeA', 'VS', 'EW', 'MGD', 'MGV', 'MZMG', 'MGM', 'DS', 'Aq', 'IF', 'InC', 'PN', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'RMC', 'mlf', 'DpG', 'DpWh', 'PaR', 'PIF', 'RSGa', 'V2L', 'IPR', 'IPL', 'IPC', 'DpMe', 'SNCM', 'SNCV', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'DT', 'Post', 'Su3', 'SubB', 'tth', 'Su3C', 'IPDM', 'dtgd', '3PC', '3N', 'bas', 'CLi', 'DIEnt', 'IPDL', 'pcer', 'ts', 'VIEnt', 'scpd', 'rs', 'RRF', 'me5', 'Me5', 'IPI', 'PaS', 'PrS'],
88 : ['MoDG', 'alv', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'CA1', 'Lmol', 'dcw', 'ml', 'PRh', 'Ect', 'AuD', 'AuV', 'Au1', 'Apir', 'V2MM', 'V2ML', 'SNR', 'SNCD', 'TeA', 'VS', 'EW', 'MGV', 'MZMG', 'DS', 'Aq', 'InC', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'RMC', 'mlf', 'DpG', 'DpWh', 'PaR', 'PIF', 'RSGa', 'V2L', 'IPR', 'IPL', 'IPC', 'DpMe', 'SNCM', 'SNCV', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'Su3', 'SubB', 'tth', 'Su3C', 'dtgd', '3PC', '3N', 'bas', 'CLi', 'DIEnt', 'IPDL', 'ts', 'VIEnt', 'scpd', 'rs', 'RRF', 'me5', 'Me5', 'IPI', 'PaS', 'PrS', 'VLPAG', 'tfp', 's5', 'm5', 'BIC'],
89 : ['MoDG', 'alv', 'GrDG', 'Or', 'RSD', 'RSGc', 'Py', 'dhc', 'Rad', 'CA1', 'Lmol', 'dcw', 'ml', 'PRh', 'Ect', 'AuD', 'AuV', 'Au1', 'V2MM', 'V2ML', 'SNR', 'TeA', 'VS', 'EW', 'DS', 'Aq', 'InC', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'mlf', 'DpG', 'DpWh', 'RSGa', 'V2L', 'IPL', 'IPC', 'DpMe', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'Su3', 'SubB', 'tth', 'Su3C', '3PC', '3N', 'bas', 'CLi', 'DIEnt', 'IPDL', 'ts', 'VIEnt', 'scpd', 'rs', 'RRF', 'me5', 'Me5', 'IPI', 'PaS', 'PrS', 'VLPAG', 'tfp', 's5', 'm5', 'BIC', 'CEnt', 'ID', 'IPA', 'Pn', 'PPTg', 'VTA'],
90 : ['unnamed', 'MoDG', 'A29c', 'A30', 'dhc', 'CA1', 'ml', 'AuD', 'Ect', 'PRh', 'Au1', 'AuV', 'DLEnt', 'cp', 'TeA', 'V2L', 'V2ML', 'V2MM', 'VS', 'Aq', 'DS', 'InC', 'InWh', '3N', '3PC', 'A29b', 'alv', 'bas', 'bic', 'BIC', 'CEnt', 'CLi', 'DIEnt', 'DLPAG', 'DMPAG', 'EW', 'ID', 'InG', 'IPA', 'IPC', 'IPDL', 'IPI', 'IPL', 'LPAG', 'm5', 'mDR', 'me5', 'MEnt', 'MiTg', 'mlf', 'MoS', 'mRT', 'Op', 'PaS', 'Pn', 'Post', 'PTg', 'PrS', 'RRF', 'rs', 's5', 'xscp', 'Su3', 'Su3C', 'SubB', 'SuG', 'tfp', 'ts', 'tth', 'V1B', 'V1M', 'VIEnt', 'VLPAG', 'VTA', 'Zo'],
91 : ['a', 'alv', 'RSD', 'dhc', 'dcw', 'ml', 'PRh', 'Ect', 'V2MM', 'V2ML', 'TeA', 'Aq', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'mlf', 'DpG', 'DpWh', 'RSGa', 'V2L', 'IPL', 'IPC', 'DpMe', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'Su3', 'SubB', 'tth', 'Su3C', '3PC', '3N', 'bas', 'CLi', 'DIEnt', 'ts', 'VIEnt', 'scpd', 'rs', 'RRF', 'me5', 'Me5', 'IPI', 'PaS', 'PrS', 'VLPAG', 'tfp', 's5', 'm5', 'BIC', 'CEnt', 'ID', 'IPA', 'Pn', 'PPTg', 'MoS', 'MiTg', 'DR', 'B9', 'ECIC', 'PBG', 'PrCnF', 'Rbd', 'STr'],
92 : ['unnamed', 'a', 'A30', 'dhc', 'ml', 'Ect', 'PRh', 'DLEnt', 'cp', 'TeA', 'V2L', 'V2ML', 'V2MM', 'Aq', 'InWh', 'A29b', 'bas', 'bic', 'BIC', 'CEnt', 'CLi', 'DIEnt', 'DLPAG', 'DMPAG', 'DpG', 'ID', 'InG', 'IPA', 'IPC', 'IPL', 'LPAG', 'm5', 'mDR', 'me5', 'MEnt', 'MiTg', 'mlf', 'MoS', 'Op', 'PaS', 'Pn', 'Post', 'PTg', 'PrS', 'RRF', 'rs', 's5', 'Su3', 'Su3C', 'SubB', 'SuG', 'ts', 'tth', 'V1B', 'V1M', 'VIEnt', 'VLPAG', 'Zo', '4N', '4Sh', 'DpWh', 'ECIC', 'isRT', 'll', 'mcp', 'PBG', 'PiSt', 'PMnR', 'PrCnF', 'Rbd', 'STr', 'SuL', 'v'],
93 : ['a', 'alv', 'RSD', 'dcw', 'ml', 'PRh', 'Ect', 'V2MM', 'V2ML', 'TeA', 'Aq', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'mlf', 'DpG', 'DpWh', 'RSGa', 'V2L', 'IPL', 'IPC', 'DpMe', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'tth', 'bas', 'CLi', 'DIEnt', 'ts', 'VIEnt', 'scpd', 'rs', 'RRF', 'me5', 'Me5', 'PaS', 'PrS', 'VLPAG', 'tfp', 's5', 'm5', 'BIC', 'CEnt', 'Pn', 'PPTg', 'MiTg', 'B9', 'ECIC', 'PBG', 'PrCnF', 'Rbd', 'STr', 'v', 'PMnR', 'PiSt', 'mcp', 'II', 'DRD', '4Sh', '4N', 'DRL', 'DRV', 'MnR', 'PDR', 'PnO', 'RR'],
94 : ['2', 'a', '1', 'alv', 'RSD', 'edb3c9', '231f20', 'dcw', 'ml', 'PRh', 'Ect', 'V2MM', 'V2ML', 'TeA', 'Aq', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'mlf', 'DpG', 'DpWh', 'V2L', 'DpMe', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'tth', 'bas', 'CLi', 'DIEnt', 'ts', 'VIEnt', 'scpd', 'rs', 'me5', 'Me5', 'PaS', 'PrS', 'VLPAG', 'tfp', 's5', 'm5', 'BIC', 'CEnt', 'Pn', 'PPTg', 'MiTg', 'B9', 'ECIC', 'PBG', 'PrCnF', 'Rbd', 'STr', 'PMnR', 'mcp', 'II', 'DRD', '4Sh', '4N', 'DRL', 'DRV', 'MnR', 'PDR', 'PnO', 'RR', 'Pi', 'Pa4', 'lfp', '6', '4n', '3/4'],
95 : ['a', 'alv', 'RSD', 'dcw', 'ml', 'PRh', 'Ect', 'V2MM', 'V2ML', 'TeA', 'Aq', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'mlf', 'DpG', 'DpWh', 'RSGa', 'V2L', 'DpMe', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'tth', 'bas', 'DIEnt', 'ts', 'VIEnt', 'scpd', 'rs', 'me5', 'Me5', 'PaS', 'PrS', 'VLPAG', 'tfp', 's5', 'm5', 'BIC', 'CEnt', 'Pn', 'PPTg', 'MiTg', 'B9', 'ECIC', 'PBG', 'PrCnF', 'Rbd', 'STr', 'v', 'PMnR', 'mcp', 'II', 'DRD', '4Sh', '4N', 'DRL', 'DRV', 'MnR', 'PDR', 'PnO', 'RR', 'Pi', 'Pa4', 'lfp', '4n'],
96 : ['a', 'alv', 'RSD', 'dcw', 'ml', 'PRh', 'Ect', 'scp', 'V2MM', 'V2ML', 'TeA', 'Aq', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'mlf', 'DpG', 'DpWh', 'RSGa', 'V2L', 'DpMe', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'tth', 'bas', 'ts', 'VIEnt', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'BIC', 'CEnt', 'Pn', 'PPTg', 'MiTg', 'B9', 'ECIC', 'PBG', 'PrCnF', 'Rbd', 'STr', 'PMnR', 'mcp', 'II', 'DRD', 'DRL', 'DRV', 'MnR', 'PDR', 'PnO', 'RR', 'Pi', 'Pa4', 'lfp', '4n', 'SPTg', 'dscp', 'Atg'],
97 : ['a', 'RSD', 'dcw', 'ml', 'PRh', 'Ect', 'V2MM', 'V2ML', 'TeA', 'Aq', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'mlf', 'DpG', 'DpWh', 'RSGa', 'V2L', 'DpMe', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'tth', 'ts', 'VIEnt', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'BIC', 'CEnt', 'Pn', 'PPTg', 'MiTg', 'ECIC', 'PBG', 'PrCnF', 'Rbd', 'PMnR', 'mcp', 'II', 'DRD', 'DRL', 'DRV', 'MnR', 'PDR', 'PnO', 'RR', 'Pi', 'Pa4', 'lfp', '4n', 'SPTg', 'dscp', 'Atg', 'PL', 'VLL'],
98 : ['a', 'RSD', 'dcw', 'ml', 'PRh', 'Ect', 'scp', 'V2MM', 'V2ML', 'TeA', 'Aq', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Op', 'SuG', 'Zo', 'mlf', 'DpG', 'DpWh', 'RSGa', 'V2L', 'DpMe', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'tth', 'bas', 'ts', 'VIEnt', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'BIC', 'CEnt', 'Pn', 'PPTg', 'MiTg', 'ECIC', 'PBG', 'PrCnF', 'Rbd', 'v', 'PMnR', 'mcp', 'II', 'DRD', 'DRL', 'DRV', 'MnR', 'PDR', 'PnO', 'Pi', 'Pa4', 'lfp', '4n', 'SPTg', 'dscp', 'Atg', 'PL', 'VLL', 'Tr', 'RtTg', 'ERS', 'CnFV', 'CnFI', 'cic', 'CIC'],
99 : ['2', '3', 'a', '1', 'RSD', 'ml', 'PRh', 'Ect', 'scp', 'V2MM', 'TeA', 'Aq', 'InWh', 'DMPAG', 'fmj', 'InG', 'LPAG', 'Zo', 'mlf', 'DpG', 'DpWh', 'RSGa', 'V2L', 'DpMe', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'tth', 'bas', 'ts', 'VIEnt', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'CEnt', 'Pn', 'PPTg', 'MiTg', 'ECIC', 'PBG', 'PrCnF', 'Rbd', 'PMnR', 'mcp', 'II', 'DRD', 'DRL', 'DRV', 'MnR', 'PDR', 'PnO', 'Pi', 'lfp', '4n', 'SPTg', 'PL', 'VLL', 'Tr', 'RtTg', 'ERS', 'CnFV', 'CnFI', 'cic', 'CIC', 'Com', 'ILL', 'MPL', 'RtTgP'],
100 : ['2', '3', 'a', '1', 'RSD', 'ml', 'PRh', 'Ect', 'scp', 'V2MM', 'TeA', 'Aq', 'DMPAG', 'fmj', 'LPAG', 'mlf', 'DpG', 'DpWh', 'RSGa', 'V2L', 'DpMe', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'tth', 'bas', 'ts', 'VIEnt', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'CEnt', 'Pn', 'PPTg', 'MiTg', 'B9', 'ECIC', 'PrCnF', 'Rbd', 'PMnR', 'mcp', 'II', 'DRD', 'DRL', 'DRV', 'MnR', 'PDR', 'PnO', 'Pi', 'lfp', '4n', 'SPTg', 'VLL', 'Tr', 'RtTg', 'CnFV', 'CnFI', 'cic', 'CIC', 'Com', 'ILL', 'MPL', 'RtTgP', 'VTg', 'DLL', 'cll'],
101 : ['2', '3', 'a', '1', 'RSD', 'ml', 'PRh', 'Ect', 'scp', 'V2MM', 'TeA', 'Aq', 'DMPAG', 'fmj', 'LPAG', 'mlf', 'RSGa', 'V2L', 'V1M', 'V1BB', 'Ment', 'DLPAG', 'bic', 'Post', 'tth', 'bas', 'ts', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'CEnt', 'Pn', 'PPTg', 'MiTg', 'ECIC', 'Rbd', 'v', 'PMnR', 'mcp', 'II', 'DRD', 'DRV', 'MnR', 'PDR', 'PnO', 'Pi', 'lfp', '4n', 'SPTg', 'VLL', 'Tr', 'RtTg', 'CnFV', 'CnFI', 'cic', 'CIC', 'Com', 'ILL', 'MPL', 'RtTgP', 'VTg', 'DLL', 'cll', 'CnFD', 'DCIC', 'LDTg'],
102 : ['2', '3', 'a', '1', 'RSD', 'ml', 'PRh', 'Ect', 'scp', 'V2MM', 'TeA', 'Aq', 'DMPAG', 'LPAG', 'mlf', 'RSGa', 'V2L', 'V1M', 'V1BB', 'Ment', 'bic', 'Post', 'tth', 'bas', 'ts', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'CEnt', 'Pn', 'PPTg', 'ECIC', 'Rbd', 'v', 'PMnR', 'mcp', 'II', 'DRD', 'DRV', 'MnR', 'PnO', 'Pi', 'lfp', '4n', 'SPTg', 'VLL', 'Tr', 'RtTg', 'CnFV', 'CnFI', 'cic', 'CIC', 'Com', 'ILL', 'MPL', 'RtTgP', 'VTg', 'DLL', 'cll', 'CnFD', 'DCIC', 'LDTg', 'Sag', 'DPPn', 'A7'],
103 : ['2', '3', 'a', '1', 'RSD', 'ml', 'PRh', 'Ect', 'scp', 'V2MM', 'TeA', 'Aq', 'DMPAG', 'LPAG', 'mlf', 'RSGa', 'V2L', 'V1M', 'V1BB', 'Ment', 'Post', 'tth', 'bas', 'ts', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'CEnt', 'Pn', 'PPTg', 'ECIC', 'Rbd', 'PMnR', 'mcp', 'II', 'DRD', 'DRV', 'MnR', 'PnO', 'Pi', 'lfp', '4n', 'SPTg', 'VLL', 'Tr', 'RtTg', 'CnFV', 'CnFI', 'CIC', 'ILL', 'MPL', 'RtTgP', 'VTg', 'DLL', 'cll', 'CnFD', 'DCIC', 'LDTg', 'Sag', 'A7', '2Cb', 'PLV'],
104 : ['2', '3', 'a', '1', 'RSD', 'ml', 'PRh', 'Ect', 'LEnt', 'scp', 'V2MM', 'TeA', 'DMPAG', 'LPAG', 'mlf', 'RSGa', 'V2L', 'V1M', 'V1BB', 'Ment', 'tth', 'bas', 'ts', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'CEnt', 'Pn', 'PPTg', 'ECIC', 'PMnR', 'mcp', 'II', 'MnR', 'PnO', 'Pi', 'lfp', '4n', 'SPTg', 'VLL', 'Tr', 'RtTg', 'CnFV', 'CnFI', 'CIC', 'ILL', 'MPL', 'RtTgP', 'VTg', 'DLL', 'CnFD', 'DCIC', 'LDTg', 'Sag', 'A7', '2Cb', 'PLV', '4V', 'DRC', 'DTgP', 'LDTgV', 'ReIC'],
105 : ['2', '3', 'a', '1', 'RSD', 'ml', 'PRh', 'Ect', 'LEnt', 'scp', 'V2MM', 'TeA', 'DMPAG', 'LPAG', 'mlf', 'V2L', 'V1M', 'V1BB', 'Ment', 'tth', 'bas', 'ts', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'CEnt', 'Pn', 'PPTg', 'ECIC', 'v', 'PMnR', 'mcp', 'II', 'MnR', 'PnO', 'Pi', 'lfp', '4n', 'VLL', 'Tr', 'RtTg', 'CnFV', 'CnFI', 'CIC', 'ILL', 'MPL', 'VTg', 'DLL', 'CnFD', 'DCIC', 'LDTg', 'Sag', 'A7', '2Cb', 'PLV', '4V', 'DRC', 'DTgP', 'LDTgV', 'ReIC', 'CAT', 'DMTg', 'KF', 'LPB', 'LPBS', 'MPB', 'MVPO', 'RL', 'tz', 'vsc'],
106 : ['2', '3', '1', 'RSD', 'ml', 'PRh', 'Ect', 'LEnt', 'scp', 'V2MM', 'TeA', 'DMPAG', 'mlf', 'V2L', 'V1M', 'V1BB', 'tth', 'bas', 'ts', 'rs', 'me5', 'Me5', 'PaS', 'VLPAG', 'tfp', 's5', 'm5', 'CEnt', 'PPTg', 'ECIC', 'v', 'PMnR', 'mcp', 'II', 'MnR', 'PnO', 'Pi', 'lfp', '4n', 'VLL', 'RtTg', 'CIC', 'DLL', 'CnFD', 'DCIC', 'LDTg', 'Sag', 'A7', '2Cb', 'PLV', '4V', 'DRC', 'DTgP', 'LDTgV', 'ReIC', 'CAT', 'DMTg', 'KF', 'LPBS', 'MPB', 'MVPO', 'tz', 'vsc', 'Su5', 'LPBE', 'LPBC', 'CG', '4/5Cb', '3Cb', '2/3Cb'],
107 : ['2', '3', 'a', '1', 'RSD', 'ml', 'PRh', 'Ect', 'LEnt', 'scp', 'V2MM', 'mlf', 'V2L', 'V1M', 'V1BB', 'tth', 'bas', 'ts', 'rs', 'me5', 'Me5', 'PaS', 'tfp', 's5', 'm5', 'CEnt', 'ECIC', 'mcp', 'II', 'PnO', 'lfp', '4n', 'VLL', 'RtTg', 'CIC', 'DCIC', 'LDTg', 'A7', '2Cb', '4V', 'DRC', 'DTgP', 'LDTgV', 'ReIC', 'CAT', 'DMTg', 'KF', 'MPB', 'MVPO', 'RL', 'tz', 'vsc', 'Su5', 'LPBE', 'LPBC', 'CG', '4/5Cb', '3Cb', '2/3Cb', 'DTgC', 'FI', 'LPBCr', 'LPBD', 'LPBI', 'LPBV', 'P5', 'PnR', 'Pr5VL', 'SubCD', 'SubCV', 'Tz'],
108 : ['2', '3', '1', 'RSD', 'ml', 'PRh', 'Ect', 'scp', 'mlf', 'V2L', 'V1M', 'V1BB', 'tth', 'bas', 'ts', 'rs', 'me5', 'PaS', 's5', 'm5', 'CEnt', 'ECIC', 'mcp', 'II', '4n', 'VLL', 'RtTg', 'CIC', 'DCIC', 'LDTg', '2Cb', '4V', 'DRC', 'DTgP', 'LDTgV', 'ReIC', 'CAT', 'DMTg', 'KF', 'MPB', 'MVPO', 'tz', 'vsc', 'Su5', 'LPBE', 'LPBC', 'CG', '4/5Cb', '3Cb', '2/3Cb', 'DTgC', 'FI', 'LPBCr', 'LPBD', 'LPBI', 'LPBV', 'P5', 'PnR', 'Pr5VL', 'SubCD', 'SubCV', 'Tz', 'py', 'PnC', 'PC5', 'MPBE', 'cbw', 'Bar', 'A5', '5N', '4Cb'],
109 : ['2', '3', 'a', '1', 'RSD', 'ml', 'PRh', 'Ect', 'scp', 'mlf', 'V2L', 'V1M', 'V1BB', 'tth', 'bas', 'ts', 'rs', 'me5', 'PaS', 's5', 'm5', 'CEnt', 'ECIC', 'mcp', '4n', 'RtTg', 'CIC', 'DCIC', 'LDTg', '2Cb', '4V', 'DRC', 'DTgP', 'CAT', 'DMTg', 'KF', 'MPB', 'MVPO', 'tz', 'vsc', 'Su5', 'LPBE', 'LPBC', '4/5Cb', '3Cb', '2/3Cb', 'DTgC', 'FI', 'LPBCr', 'LPBD', 'LPBI', 'LPBV', 'P5', 'Pr5VL', 'SubCD', 'SubCV', 'Tz', 'py', 'PnC', 'PC5', 'MPBE', 'cbw', 'Bar', 'A5', '4Cb', '5Cb', '5Ma', '5MHy', '5Te', 'CGA', 'CGB', 'GrC', 'LVPO', 'MSO', 'SubCA', 'VCA'],
110 : ['RSD', 'ml', 'PRh', 'Ect', 'scp', 'mlf', 'V2L', 'V1M', 'V1BB', 'tth', 'bas', 'ts', 'rs', 'me5', 'PaS', 's5', 'm5', 'CEnt', 'ECIC', 'mcp', '4n', 'RtTg', 'DCIC', 'LDTg', '2Cb', '4V', 'DRC', 'DTgP', 'DMTg', 'KF', 'MPB', 'MVPO', 'tz', 'vsc', 'Su5', 'LPBE', 'LPBC', '3Cb', 'DTgC', 'FI', 'LPBCr', 'LPBD', 'LPBI', 'LPBV', 'P5', 'Pr5VL', 'SubCD', 'SubCV', 'Tz', 'py', 'PnC', 'PC5', 'MPBE', 'cbw', 'Bar', 'A5', '4Cb', '5Cb', '5Ma', '5MHy', '5Te', 'CGA', 'CGB', 'GrC', 'LVPO', 'MSO', 'SubCA', 'VCA', '2bCb', 'CGO', 'SPO'],
111 : ['RSD', 'ml', 'PRh', 'Ect', 'scp', 'mlf', 'V2L', 'V1M', 'V1BB', 'tth', 'bas', 'ts', 'rs', 'me5', 's5', 'm5', 'CEnt', 'DR', 'mcp', '4n', 'RtTg', 'LDTg', '2Cb', '4V', 'DMTg', 'LPB', 'MPB', 'MVPO', 'tz', 'vsc', 'Su5', 'LPBE', 'LPBC', '3Cb', 'FI', 'LPBI', 'LPBV', 'P5', 'Pr5VL', 'SubCD', 'SubCV', 'Tz', 'py', 'PnC', 'PC5', 'MPBE', 'cbw', 'Bar', 'A5', '4Cb', '5Cb', '5Ma', '5Te', 'CGA', 'CGB', 'GrC', 'LVPO', 'MSO', 'SubCA', 'VCA', 'CGO', 'SPO', 'Sph', 'Sim', 'Pr5DM', 'PDTg', 'PCGS', 'IC', '7n', '5VM'],
112 : ['unnamed', 'ml', 'scp', 'bas', 'CEnt', 'm5', 'me5', 'mlf', 's5', 'ts', 'tth', 'mcp', '1Cb', '3Cb', '4Cb', '4n', '4V', '5Cb', '5Ma', '5Te', '5MHy', '7n', '8cn', 'Bar', 'cbw', 'CGA', 'CGB', 'CGO', 'Cx', 'DMTg', 'Fl', 'GrC', 'LC', 'LDTg', 'LPB', 'LPBI', 'LPBV', 'LSO', 'LVPO', 'Me5', 'MPB', 'MSO', 'MVPO', 'P5', 'PCGS', 'PDTg', 'POH', 'Pr5DM', 'Pr5VL', 'py', 'RtTg', 'RtTgL', 'RIP', 'Sim', 'Sph', 'SPO', 'Su5', 'SubCD', 'tz', 'Tz', 'VCA', 'vsc', 'IF5', 'RMg'],
113 : ['unnamed', 'a', 'ml', 'scp', 'bas', 'm5', 'me5', 'mlf', 's5', 'ts', 'tth', 'mcp', '1Cb', '2Cb', '3Cb', '4V', '5Cb', '5Ma', '5Te', '5MHy', '7n', '8cn', 'cbw', 'CGA', 'CGB', 'CGO', 'Cx', 'DMTg', 'Fl', 'GrC', 'LC', 'LPB', 'LPBI', 'LPBV', 'LSO', 'LVPO', 'Me5', 'MPB', 'MSO', 'MVPO', 'P5', 'PCGS', 'PDTg', 'POH', 'Pr5DM', 'Pr5VL', 'py', 'RtTg', 'RtTgL', 'RIP', 'Sim', 'Sph', 'SPO', 'Su5', 'SubCD', 'tz', 'Tz', 'VCA', 'vsc', 'RMg', '5ADi', '5Tr', 'DPO', 'LR4V', 'PFl ', 'PnV', 'scpd', 'CG'],
114 : ['unnamed', 'a', 'scp', 'bas', 'm5', 'me5', 'mlf', 's5', 'ts', 'tth', 'mcp', '1Cb', '2Cb', '3Cb', '4V', '5Cb', '5Ma', '5Te', '7n', '8cn', 'NA5', 'cbw', 'CGA', 'CGB', 'CGO', 'DMTg', 'Fl', 'GrC', 'LC', 'LPB', 'LSO', 'LVPO', 'Me5', 'MSO', 'MVPO', 'P5', 'PCGS', 'PDTg', 'POH', 'Pr5DM', 'Pr5VL', 'py', 'RtTgL', 'RIP', 'SPO', 'SubCD', 'tz', 'Tz', 'VCA', 'vsc', 'RMg', '5ADi', '5Tr', 'DPO', 'LR4V', 'PFl ', 'PnV', 'scpd', 'CG', 'SimA', 'SimB', 'SuVe'],
115 : ['ml', 'scp', 'mlf', 'tth', 'bas', 'ts', 'scpd', 'rs', 'me5', 's5', 'm5', 'mcp', '2Cb', '4V', 'DMTg', 'MPB', 'MVPO', 'tz', 'vsc', '3Cb', 'FI', 'P5', 'Pr5VL', 'SubCD', 'SubCV', 'Tz', 'py', 'PnC', 'cbw', 'A5', '4Cb', '5Cb', '5Ma', '5Te', 'CGA', 'CGB', 'GrC', 'LVPO', 'MSO', 'VCA', 'SPO', 'Pr5DM', 'PDTg', 'PCGS', '7n', 'POH', 'LSO', 'LC', '8cn', '1Cb', '5Acs', '5Tr', 'CGPn', 'DPO', 'LR4V', 'PFI', 'PnV', 'RIP', 'RMg', 'Rpa', 'SimA', 'SimB', 'SuVe', 'un', 'PCRt', 'ocb', 'MVeMC', 'II', 'CGG', '8vn', '6n'],
116 : ['ml', 'scp', 'mlf', 'IPR', 'tth', 'bas', 'ts', 'rs', 's5', 'mcp', '2Cb', '4V', 'MPB', 'MVPO', 'tz', 'vsc', '3Cb', 'FI', 'P5', 'Pr5VL', 'SubCD', 'SubCV', 'Tz', 'py', 'PnC', 'cbw', 'A5', '4Cb', '5Cb', 'CGA', 'GrC', 'LVPO', 'MSO', 'VCA', 'SPO', 'Pr5DM', 'PCGS', '7n', 'POH', 'LSO', 'LC', '8cn', '1Cb', '5Acs', '5Tr', 'DPO', 'LR4V', 'PFI', 'PnV', 'RIP', 'RMg', 'Rpa', 'SimA', 'SimB', 'SuVe', 'un', 'PCRt', 'ocb', 'MVeMC', 'II', 'CGG', '8vn', '6n', 'Eve', 'icp', 'Sge', 'veme'],
117 : ['ml', 'scp', 'mlf', 'tth', 'bas', 'ts', 'rs', 's5', 'mcp', '2Cb', '4V', 'MVPO', 'tz', 'vsc', '3Cb', 'FI', 'Pr5VL', 'Tz', 'py', 'PnC', 'cbw', 'A5', '4Cb', '5Cb', 'CGA', 'GrC', 'LVPO', 'MSO', 'VCA', 'SPO', 'Pr5DM', 'PCGS', '7n', 'LSO', 'LC', '8cn', '1Cb', '5Tr', 'LR4V', 'PFI', 'PnV', 'RIP', 'RMg', 'Rpa', 'SimA', 'SimB', 'SuVe', 'un', 'ocb', 'MVeMC', 'CGG', '8vn', 'Eve', 'icp', 'Sge', 'veme', 'PCRtA', 'Pa6', 'MVePC', 'IRt', 'Crus1', '6N', '6Acs'],
118 : ['a', '2abbb4', 'ml', 'scp', 'mlf', 'bas', 'ts', 'rs', 'mcp', '2Cb', '4V', 'MVPO', 'tz', 'vsc', '3Cb', 'FI', 'Pr5VL', 'Tz', 'py', 'PnC', 'cbw', 'A5', '4Cb', '5Cb', 'CGA', 'GrC', 'LVPO', 'MSO', 'VCA', 'SPO', 'Pr5DM', 'PCGS', '7n', 'LSO', 'LC', '1Cb', 'DPO', 'LR4V', 'PFI', 'PnV', 'RIP', 'RMg', 'Rpa', 'SimA', 'SimB', 'SuVe', 'un', 'ocb', 'MVeMC', 'CGG', '8vn', 'Eve', 'icp', 'Sge', 'veme', 'PCRtA', 'Pa6', 'MVePC', 'IRt', 'Crus1', '6N', '6Acs', 'SuS', 'sp5', 'g7'],
119 : ['2abbb4', 'ml', 'scp', 'mlf', 'bas', 'ts', 'rs', '2Cb', '4V', 'MVPO', 'tz', 'vsc', '3Cb', 'FI', 'Pr5VL', 'Tz', 'py', 'cbw', 'A5', '4Cb', '5Cb', 'GrC', 'LVPO', 'MSO', 'VCA', 'SPO', 'Pr5DM', 'PCGS', '7n', 'LSO', 'LC', '1Cb', 'DPO', 'LR4V', 'PFI', 'PnV', 'RIP', 'RMg', 'Rpa', 'SimA', 'SimB', 'SuVe', 'un', 'ocb', 'MVeMC', '8vn', 'Eve', 'Sge', 'veme', 'PCRtA', 'Pa6', 'MVePC', 'IRt', 'Crus1', '6N', '6Acs', 'SuS', 'sp5', 'g7', 'Gi', 'GiA', 'LPGi', 'Pr'],
120 : ['a', 'ml', 'scp', 'mlf', 'tth', 'bas', 'ts', 'rs', '2Cb', '4V', 'MVPO', 'tz', 'vsc', '3Cb', 'FI', 'Pr5VL', 'Tz', 'py', 'cbw', 'A5', '4Cb', '5Cb', 'GrC', 'MSO', 'VCA', 'SPO', 'LSO', '1Cb', 'LR4V', 'PFI', 'RMg', 'Rpa', 'SimA', 'SimB', 'SuVe', 'un', 'ocb', 'MVeMC', '8vn', 'Eve', 'icp', 'veme', 'PCRtA', 'Pa6', 'MVePC', 'Crus1', '6Acs', 'SuS', 'sp5', 'g7', 'Gi', 'GiA', 'LPGi', 'Pr', 'VCP', 'Sp5O', 'P7', 'MoCb', 'IRtA', 'GrCb', 'DPGi', 'DMSp5', 'cbc ', '7Acs']
}
"""lst=[]
for i in regs_per_section.values():
    for j in i :
        lst.append(j.strip()+"_R")
        lst.append(j.strip()+"_L")
with open ("regions_per_sections_rat.txt","w") as file:
    for i in set(lst):
        file.write(i+"\n")
    file.write("not detected_L\n")
    file.write("not detected_R\n")"""
Region_names = ['A32D _L', 'A32D _R', 'A32V _L', 'A32V _R', 'aca _L', 'aca _R', 'AID _L', 'AID _R', 'AIV _L', 'AIV _R', 'AOL _L', 'AOL _R', 'AOVP _L', 'AOVP _R', 'Cl _L', 'Cl _R', 'DEn _L', 'DEn _R', 'DTr _L', 'DTr _R', 'DTT1 _L', 'DTT1 _R', 'DTT2 _L', 'DTT2 _R', 'DTT3  _L', 'DTT3  _R', 'RMS/OV _L', 'RMS/OV _R', 'fmi _L', 'fmi _R', 'Fr3 _L', 'Fr3 _R', 'IEn _L', 'IEn _R', 'lo _L', 'lo _R', 'LO _L', 'LO _R', 'lofr _L', 'lofr _R', 'M1 _L', 'M1 _R', 'M2 _L', 'M2 _R', 'MO _L', 'MO _R', 'mofr _L', 'mofr _R', 'Pir1a _L', 'Pir1a _R', 'Pir1b _L', 'Pir1b _R', 'Pir2 _L', 'Pir2 _R', 'Pir3 _L', 'Pir3 _R', 'VO _L', 'VO _R', 'VTT1 _L', 'VTT1 _R', 'VTT2 _L', 'VTT2 _R', 'VTT3 _L', 'VTT3 _R', 'AOP _L', 'AOP _R', 'DP _L', 'DP _R', 'Pir1 _L', 'Pir1 _R', 'A25 _L', 'A25 _R', 'AcbSh _L', 'AcbSh _R', 'azac _L', 'azac _R', 'DI _L', 'DI _R', 'ICj _L', 'ICj _R', 'Nv _L', 'Nv _R', 'S1J _L', 'S1J _R', 'Tu1 _L', 'Tu1 _R', 'Tu2 _L', 'Tu2 _R', 'Tu3 _L', 'Tu3 _R', 'A24a _L', 'A24a _R', 'A24b _L', 'A24b _R', 'AcbC _L', 'AcbC _R', 'azp _L', 'azp _R', 'CPu _L', 'CPu _R', 'GI _L', 'GI _R', 'mfb _L', 'mfb _R', 'VP _L', 'VP _R', 'A33 _L', 'A33 _R', 'cc _L', 'cc _R', 'E _L', 'E _R', 'ec _L', 'ec _R', 'IG _L', 'IG _R', 'LSI _L', 'LSI _R', 'LSS _L', 'LSS _R', 'LV _L', 'LV _R', 'S1DZ _L', 'S1DZ _R', 'S1DZO _L', 'S1DZO _R', 'S1FL _L', 'S1FL _R', 'S1ULp _L', 'S1ULp _R', 'SHi _L', 'SHi _R', 'acer _L', 'acer _R', 'DCI _L', 'DCI _R', 'ICjM _L', 'ICjM _R', 'LAcbSh _L', 'LAcbSh _R', 'LSD _L', 'LSD _R', 'LSV _L', 'LSV _R', 'Tu _L', 'Tu _R', 'VCI _L', 'VCI _R', 'PDZ _L', 'PDZ _R', 'VDB _L', 'VDB _R', 'CB _L', 'CB _R', 'HDB _L', 'HDB _R', 'Ld _L', 'Ld _R', 'mcer _L', 'mcer _R', 'MS _L', 'MS _R', 'PLd _L', 'PLd _R', 'S2 _L', 'S2 _R', 'SIB _L', 'SIB _R', 'unnamed _L', 'unnamed _R', '3V _L', '3V _R', 'AA _L', 'AA _R', 'acp _L', 'acp _R', 'AIP _L', 'AIP _R', 'B _L', 'B _R', 'BAC _L', 'BAC _R', 'CxA1 _L', 'CxA1 _R', 'CxA2 _L', 'CxA2 _R', 'CxA3 _L', 'CxA3 _R', 'DA14 _L', 'DA14 _R', 'EGP _L', 'EGP _R', 'f _L', 'f _R', 'ic _L', 'ic _R', 'IPACL _L', 'IPACL _R', 'IPACM _L', 'IPACM _R', 'LOT _L', 'LOT _R', 'LPO _L', 'LPO _R', 'LTer _L', 'LTer _R', 'MPA _L', 'MPA _R', 'MPOC _L', 'MPOC _R', 'MPOL _L', 'MPOL _R', 'MPOM _L', 'MPOM _R', 'och _L', 'och _R', 'Pe _L', 'Pe _R', 'S1BF _L', 'S1BF _R', 'S1HL _L', 'S1HL _R', 'SCh _L', 'SCh _R', 'SHy _L', 'SHy _R', 'SO _L', 'SO _R', 'st _L', 'st _R', 'STLI _L', 'STLI _R', 'STLP _L', 'STLP _R', 'STLV _L', 'STLV _R', 'STMAL _L', 'STMAL _R', 'STMAM _L', 'STMAM _R', 
'TS _L', 'TS _R', 'VLPO _L', 'VLPO _R', 'a _L', 'a _R', 'ACo _L', 'ACo _R', 'fi _L', 'fi _R', 'LOT1 _L', 'LOT1 _R', 'LOT2 _L', 'LOT2 _R', 'mch _L', 'mch _R', 'PDPO _L', 'PDPO _R', 'PaAP _L', 'PaAP _R', 'SFO _L', 'SFO _R', 'sm _L', 'sm _R', 'sox _L', 'sox _R', 'StHy _L', 'StHy _R', 'STMPI _L', 'STMPI _R', 'STMPL _L', 'STMPL _R', 'STMPM _L', 'STMPM _R', 'AD _L', 'AD _R', 'AHC _L', 'AHC _R', 'AM _L', 'AM _R', 'AMV _L', 'AMV _R', 'ANS _L', 'ANS _R', 'aot _L', 'aot _R', 'ASt _L', 'ASt _R', 'AVDM _L', 'AVDM _R', 'AVVL _L', 'AVVL _R', 'BAOT _L', 'BAOT _R', 'BLA _L', 'BLA _R', 'BMA _L', 'BMA _R', 'CeC _L', 'CeC _R', 'CeM _L', 'CeM _R', 'CM _L', 'CM _R', 'cst _L', 'cst _R', 'D3V _L', 'D3V _R', 'df _L', 'df _R', 'IAD _L', 'IAD _R', 'IGP _L', 'IGP _R', 'LDB _L', 'LDB _R', 'MeAD _L', 'MeAD _R', 'MoDG _L', 'MoDG _R', 'opt _L', 'opt _R', 'PaMM _L', 'PaMM _R', 'PaMP _L', 'PaMP _R', 'PaV _L', 'PaV _R', 'PaXi _L', 'PaXi _R', 'PC _L', 'PC _R', 'PLH _L', 'PLH _R', 'PT _L', 'PT _R', 'PVA _L', 'PVA _R', 'RCh _L', 'RCh _R', 'RChL _L', 'RChL _R', 'Re _L', 'Re _R', 'Rt _L', 'Rt _R', 'RtSt _L', 'RtSt _R', 'S1Sh _L', 'S1Sh _R', 'STSL _L', 'STSL _R', 'STSM _L', 'STSM _R', 'VA _L', 'VA _R', 'VEn _L', 'VEn _R', 'vhc _L', 'vhc _R', 'VLH _L', 'VLH _R', 'VRe _L', 'VRe _R', 'Xi _L', 'Xi _R', 'EA _L', 'EA _R', 'A29c _L', 'A29c _R', 'A30 _L', 'A30 _R', 'AHP _L', 'AHP _R', 'ArcD _L', 'ArcD _R', 'ArcL _L', 'ArcL _R', 'ArcM _L', 'ArcM _R', 'BLV _L', 'BLV _R', 'CA2 _L', 'CA2 _R', 'CA3 _L', 'CA3 _R', 'CeL _L', 'CeL _R', 'dhc _L', 'dhc _R', 'EP _L', 'EP _R', 'GrDG _L', 'GrDG _R', 'IM _L', 'IM _R', 'LDVL _L', 'LDVL _R', 'MD _L', 'MD _R', 'MeAV _L', 'MeAV _R', 'MEE _L', 'MEE _R', 'MHb _L', 'MHb _R', 'mt _L', 'mt _R', 'PaDC _L', 'PaDC _R', 'Rh _L', 'Rh _R', 'SLu _L', 'SLu _R', 'SOR _L', 'SOR _R', 'vlh _L', 'vlh _R', 'VM _L', 'VM _R', 'VMHSh _L', 'VMHSh _R', 'ZIR _L', 'ZIR _R', 'Ang _L', 'Ang _R', 'BLP _L', 'BLP _R', 'CA1 _L', 'CA1 _R', 'DA _L', 'DA _R', 'DA13 _L', 'DA13 _R', 'DMD _L', 'DMD _R', 'I\n _L', 'I\n _R', 'IMD _L', 'IMD _R', 'LaDL _L', 'LaDL _R', 'LDDM _L', 'LDDM _R', 'LHb _L', 'LHb _R', 'MDL _L', 'MDL _R', 'MDM _L', 'MDM _R', 'MePD _L', 'MePD _R', 'PeFLH _L', 'PeFLH _R', 'PLCo _L', 'PLCo _R', 'PoDG _L', 'PoDG _R', 'PV _L', 'PV _R', 'S1Tr _L', 'S1Tr _R', 'STIA _L', 'STIA _R', 'SubD _L', 'SubD _R', 'SubV _L', 'SubV _R', 'VL _L', 'VL _R', 'VMHC _L', 'VMHC _R', 'VMHDM _L', 'VMHDM _R', 'VMHVL _L', 'VMHVL _R', 'VPL _L', 'VPL _R', 'BMP _L', 'BMP _R', 'IMG _L', 'IMG _R', 'LaVL _L',
'LaVL _R', 'LaVM _L', 'LaVM _R', 'LMol _L', 'LMol _R', 'MCLH _L', 'MCLH _R', 'MDC _L', 'MDC _R', 'MePV _L', 'MePV _R', 'ml _L', 'ml _R', 'MTu _L', 'MTu _R', 'PeF _L', 'PeF _R', 'PLCo1 _L', 'PLCo1 _R', 'PLCo2 _L', 'PLCo2 _R', 'PLCo3 _L', 'PLCo3 _R', 'PMCo _L', 'PMCo _R', 'Po _L', 'Po _R', 'SubI _L', 'SubI _R', 'VPM _L', 'VPM _R', 'ZID _L', 'ZID _R', 'ZIV _L', 'ZIV _R', 'AuD _L', 'AuD _R', 'DA11 _L', 'DA11 _R', 'DMC _L', 'DMC _R', 'Ect _L', 'Ect _R', 'FC _L', 'FC _R', 'fr _L', 'fr _R', 'LHbL _L', 'LHbL _R', 'LHbM _L', 'LHbM _R', 'MEI _L', 'MEI _R', 'p3 _L', 'p3 _R', 'PHD _L', 'PHD _R', 'PRh _L', 'PRh _R', 'PTe _L', 'PTe _R', 'PVP _L', 'PVP _R', 'RAPir _L', 'RAPir _R', 'Sub _L', 'Sub _R', 'Te _L', 'Te _R', 'AHiAL _L', 'AHiAL _R', 'Au1 _L', 'Au1 _R', 'AuV _L', 'AuV _R', 'CL _L', 'CL _R', 'DLG _L', 'DLG _R', 'DLEnt _L', 'DLEnt _R', 'DMV _L', 'DMV _R', 'eml _L', 'eml _R', 'LPMR _L', 'LPMR _R', 'LPtA _L', 'LPtA _R', 'MPtA _L', 'MPtA _R', 'ns _L', 'ns _R', 'OPC _L', 'OPC _R', 'STh _L', 'STh _R', 'VMH _L', 'VMH _R', 'ArcLP _L', 'ArcLP _R', 'ArcMP _L', 'ArcMP _R', 'InfS _L', 'InfS _R', 'LPLR _L', 'LPLR _R', 'PH _L', 'PH _R', 'PrG _L', 'PrG _R', 'scp _L', 'scp _R', 'VPPC _L', 'VPPC _R', 'AHiPM _L', 'AHiPM _R', 'APir _L', 'APir _R', 'APTD _L', 'APTD _R', 'cg _L', 'cg _R', 'cp _L', 'cp _R', 'Dk _L', 'Dk _R', 'Eth _L', 'Eth _R', 'IGL _L', 'IGL _R', 'IMA _L', 'IMA _R', 'LM _L', 'LM _R', 'LPLC _L', 'LPLC _R', 'LPMC _L', 'LPMC _R', 'LT _L', 'LT _R', 'Lth _L', 'Lth _R', 'MCPC _L', 'MCPC _R', 'MGD _L', 'MGD _R', 'MGV _L', 'MGV _R', 'ML _L', 'ML _R', 'MM _L', 'MM _R', 'mp _L', 'mp _R', 'MPT _L', 'MPT _R', 'mtg _L', 'mtg _R', 'MZMG _L', 'MZMG _R', 'OPT _L', 'OPT _R', 'PBP _L', 'PBP _R', 'pc _L', 'pc _R', 'PCom _L', 'PCom _R', 'PLi _L', 'PLi _R', 'PPA _L', 'PPA _R', 'PtPD _L', 'PtPD _R', 'PtPR _L', 'PtPR _R', 'REn _L', 'REn _R', 'REth _L', 'REth _R', 'RMM _L', 'RMM _R', 'RPF _L', 'RPF _R', 'SCO _L', 'SCO _R', 'SNCD _L', 'SNCD _R', 'SNL _L', 'SNL _R', 'SNR _L', 'SNR _R', 'SPFPC _L', 'SPFPC _R', 'str _L', 'str _R', 'Subiculum _L', 'Subiculum _R', 'TeA _L', 'TeA _R', 'V1 _L', 'V1 _R', 'V2L _L', 'V2L _R', 'V2ML _L', 'V2ML _R', 'V2MM _L', 'V2MM _R', 'VLi _L', 'VLi _R', 'VS _L', 'VS _R', 'VTAR _L', 'VTAR _R', 'VTM _L', 'VTM _R', 'ZIC _L', 'ZIC _R', 'APTV _L', 'APTV _R', 'Aq _L', 'Aq _R', 'DS _L', 'DS _R', 'IF _L', 'IF _R', 'InC _L', 'InC _R', 'InCSh _L', 'InCSh _R', 'ipf _L', 'ipf _R', 'MA3 _L', 'MA3 _R', 'MGM _L', 'MGM _R', 'MT _L', 'MT _R', 'p1 _L', 'p1 _R', 
'p1Rt _L', 'p1Rt _R', 'PIL _L', 'PIL _R', 'pIPAG _L', 'pIPAG _R', 'PP _L', 'PP _R', 'PrEW _L', 'PrEW _R', 'RLi _L', 'RLi _R', 'SG _L', 'SG _R', 'TG _L', 'TG _R', 'InWh _L', 'InWh _R', 'PaC _L', 'PaC _R', 'PN _L', 'PN _R', 'RPC _L', 'RPC _R', '3N _L', '3N _R', '3PC _L', '3PC _R', 'A29b _L', 'A29b _R', 'alv _L', 'alv _R', 'bas _L', 'bas _R', 'bic _L', 'bic _R', 'BIC _L', 'BIC _R', 'CEnt _L', 'CEnt _R', 'CLi _L', 'CLi _R', 'DIEnt _L', 'DIEnt _R', 'DLPAG _L', 'DLPAG _R', 'DMPAG _L', 'DMPAG _R', 'DpG _L', 'DpG _R', 'EW _L', 'EW _R', 'ID _L', 'ID _R', 'InG _L', 'InG _R', 'IPA _L', 'IPA _R', 'IPC _L', 'IPC _R', 'IPDL _L', 'IPDL _R', 'IPI _L', 'IPI _R', 'IPL _L', 'IPL _R', 'LPAG _L', 'LPAG _R', 'm5 _L', 'm5 _R', 'mDR _L', 'mDR _R', 'me5 _L', 'me5 _R', 'MEnt _L', 'MEnt _R', 'MiTg _L', 'MiTg _R', 'mlf _L', 'mlf _R', 'MoS _L', 'MoS _R', 'mRT _L', 'mRT _R', 'Op _L', 'Op _R', 'PaS _L', 'PaS _R', 'Pn _L', 'Pn _R', 'Post _L', 'Post _R', 'PTg _L', 'PTg _R', 'PrS _L', 'PrS _R', 'RRF _L', 'RRF _R', 'rs _L', 'rs _R', 's5 _L', 's5 _R', 'xscp _L', 'xscp _R', 'Su3 _L', 'Su3 _R', 'Su3C _L', 'Su3C _R', 'SubB _L', 'SubB _R', 'SuG _L', 'SuG _R', 'tfp _L', 'tfp _R', 'ts _L', 'ts _R', 'tth _L', 'tth _R', 'V1B _L', 'V1B _R', 'V1M _L', 'V1M _R', 'VIEnt _L', 'VIEnt _R', 'VLPAG _L', 'VLPAG _R', 'VTA _L', 'VTA _R', 'Zo _L', 'Zo _R', '4N _L', '4N _R', '4Sh _L', '4Sh _R', 'DpWh _L', 'DpWh _R', 'ECIC _L', 'ECIC _R', 'isRT _L', 'isRT _R', 'll _L', 'll _R', 'mcp _L', 'mcp _R', 'PBG _L', 'PBG _R', 'PiSt _L', 'PiSt _R', 'PMnR _L', 'PMnR _R', 'PrCnF _L', 'PrCnF _R', 'Rbd _L', 'Rbd _R', 'STr _L', 'STr _R', 'SuL _L', 'SuL _R', 'v _L', 'v _R', '1Cb _L', '1Cb _R', '2Cb _L', '2Cb _R', '3Cb _L', '3Cb _R', '4Cb _L', '4Cb _R', '4n _L', '4n _R', '4V _L', '4V _R', '5Cb _L', '5Cb _R', '5Ma _L', '5Ma _R', '5Te _L', '5Te _R', '5MHy _L', '5MHy _R', '7n _L', '7n _R', '8cn _L', '8cn _R', 'NA5 _L', 'NA5 _R', 'Bar _L', 'Bar _R', 'cbw _L', 'cbw _R', 'CGA _L', 'CGA _R', 'CGB _L', 'CGB _R', 'CGO _L', 'CGO _R', 'Cx _L', 'Cx _R', 'DMTg _L', 'DMTg _R', 'Fl _L', 'Fl _R', 'GrC _L', 'GrC _R', 'LC _L', 'LC _R', 'LDTg _L', 'LDTg _R', 'LPB _L', 'LPB _R', 'LPBI _L', 'LPBI _R', 'LPBV _L', 'LPBV _R', 'LSO _L', 'LSO _R', 'LVPO _L', 'LVPO _R', 'Me5 _L', 'Me5 _R', 'MPB _L', 'MPB _R', 'MSO _L', 'MSO _R', 'MVPO _L', 'MVPO _R', 'P5 _L', 'P5 _R', 'PCGS _L', 'PCGS _R', 'PDTg _L', 'PDTg _R', 'POH _L', 'POH _R', 'Pr5DM _L', 'Pr5DM _R', 'Pr5VL _L', 'Pr5VL _R', 'py _L', 'py _R', 'RtTg _L', 'RtTg _R', 'RtTgL _L', 'RtTgL _R', 
'A24aa _L', 'A24aa _R', 'A24bb _L', 'A24bb _R', 'RIP _L', 'RIP _R', 'Sim _L', 'Sim _R', 'Sph _L', 'Sph _R', 'SPO _L', 'SPO _R', 'Su5 _L', 'Su5 _R', 'SubCD _L', 'SubCD _R', 'tz _L', 'tz _R', 'Tz _L', 'Tz _R', 'VCA _L', 'VCA _R', 'vsc _L', 'vsc _R', 'IF5 _L', 'IF5 _R', 'RMg _L', 'RMg _R', '5ADi _L', '5ADi _R', '5Tr _L', '5Tr _R', 'DPO _L', 'DPO _R', 'LR4V _L', 'LR4V _R', 'PFl _L', 'PFl _R', 'PnV _L', 'PnV _R', 'scpd _L', 'scpd _R', 'CG _L', 'CG _R', 'SimA _L', 'SimA _R', 'SimB _L', 'SimB _R', 'SuVe _L', 'SuVe _R', 'AC _L', 'AC _R', 'ac _L', 'ac _R']
"""lst2=[]
for i in Region_names:
    if "_L" in i or "_R" in i:
        lst2.append(i.split()[0])"""


# RGB colors
Regions_n_colors_List = [('root', 'not detected', '000000', (0, 0, 0)),
('root', 'A32D', '37779d', (55, 119, 157)),
 ('root', 'A32V', 'f98700', (249, 135, 0)),
 ('root', 'aca', 'dab193', (218, 177, 147)),
 ('root', 'AID', 'd6d606', (214, 214, 6)),
 ('root', 'AIV', 'b5c90f', (181, 201, 15)),
 ('root', 'AOL', '89a396', (137, 163, 150)),
 ('root', 'AOVP', 'fabf00', (250, 191, 0)),
 ('root', 'Cl', '95ba12', (149, 186, 18)),
 ('root', 'DEn', '626a77', (98, 106, 119)),
 ('root', 'DTr', '944866', (148, 72, 102)),
 ('root', 'DTT1', '81a0d7', (129, 160, 215)),
 ('root', 'DTT2', '812333', (129, 35, 51)),
 ('root', 'DTT3 ', '855555', (133, 85, 85)),
 ('root', 'RMS/OV', '462445', (70, 36, 69)),
 ('root', 'fmi', '95a98d', (149, 169, 141)),
 ('root', 'Fr3', '6aa71b', (106, 167, 27)),
 ('root', 'IEn', '262626', (38, 38, 38)),
 ('root', 'lo', '47c1a8', (71, 193, 168)),
 ('root', 'LO', 'e2e6ef', (226, 230, 239)),
 ('root', 'lofr', '5d4037', (93, 64, 55)),
 ('root', 'M1', 'f75a53', (247, 90, 83)),
 ('root', 'M2', 'f76d02', (247, 109, 2)),
 ('root', 'MO', '828999', (130, 137, 153)),
 ('root', 'mofr', '9654b6', (150, 84, 182)),
 ('root', 'Pir1a', '56b0bb', (86, 176, 187)),
 ('root', 'Pir1b', '56a999', (86, 169, 153)),
 ('root', 'Pir2', '56b364', (86, 179, 100)),
 ('root', 'Pir3', '56b999', (86, 185, 153)),
 ('root', 'VO', 'a3abbe', (163, 171, 190)),
 ('root', 'VTT1', 'f57c00', (245, 124, 0)),
 ('root', 'VTT2', '0091ea', (0, 145, 234)),
 ('root', 'VTT3', '56b001', (86, 176, 1)),
 ('root', 'AOP', 'e8a135', (232, 161, 53)),
 ('root', 'DP', '88cb5a', (136, 203, 90)),
 ('root', 'Pir1', '7f7f7f', (127, 127, 127)),
 ('root', 'A25', 'e8d851', (232, 216, 81)),
 ('root', 'AcbSh', 'dd2c00', (221, 44, 0)),
 ('root', 'azac', '5b53a9', (91, 83, 169)),
 ('root', 'DI', '8dd0be', (141, 208, 190)),
 ('root', 'ICj', 'dd7633', (221, 118, 51)),
 ('root', 'Nv', '7c4dff', (124, 77, 255)),
 ('root', 'S1J', 'd63b3f', (214, 59, 63)),
 ('root', 'Tu1', 'b3ce1d', (179, 206, 29)),
 ('root', 'Tu2', 'b3cccc', (179, 204, 204)),
 ('root', 'Tu3', '67ddab', (103, 221, 171)),
 ('root', 'A24a', '84ffff', (132, 255, 255)),
 ('root', 'A24b', 'ff3d00', (255, 61, 0)),
 ('root', 'AcbC', '272530', (39, 37, 48)),
 ('root', 'azp', '6f64c0', (111, 100, 192)),
 ('root', 'CPu', '43b3cb', (67, 179, 203)),
 ('root', 'GI', '4b6367', (75, 99, 103)),
 ('root', 'mfb', 'b388ff', (179, 136, 255)),
 ('root', 'VP', '1d1c24', (29, 28, 36)),
 ('root', 'A33', '66bb6a', (102, 187, 106)),
 ('root', 'cc', 'e91e63', (233, 30, 99)),
 ('root', 'E', 'f44336', (244, 67, 54)),
 ('root', 'ec', '651fff', (101, 31, 255)),
 ('root', 'IG', '7aa59e', (122, 165, 158)),
 ('root', 'LSI', 'daab65', (218, 171, 101)),
 ('root', 'LSS', 'e9cd6c', (233, 205, 108)),
 ('root', 'LV', '2abbb4', (42, 187, 180)),
 ('root', 'S1DZ', 'f9644e', (249, 100, 78)),
 ('root', 'S1DZO', '117ab3', (17, 122, 179)),
 ('root', 'S1FL', '5e5c5d', (94, 92, 93)),
 ('root', 'S1ULp', 'f7f7ef', (247, 247, 239)),
 ('root', 'SHi', '2a2a2a', (42, 42, 42)),
 ('root', 'acer', '444d5c', (68, 77, 92)),
 ('root', 'DCI', '4d99cb', (77, 153, 203)),
 ('root', 'ICjM', 'ed7f5a', (237, 127, 90)),
 ('root', 'LAcbSh', '4fc3f7', (79, 195, 247)),
 ('root', 'LSD', 'd45477', (212, 84, 119)),
 ('root', 'LSV', '697466', (105, 116, 102)),
 ('root', 'Tu', '69f0ae', (105, 240, 174)),
 ('root', 'VCI', 'eca95a', (236, 169, 90)),
 ('root', 'PDZ', 'aeea00', (174, 234, 0)),
 ('root', 'VDB', 'f36861', (243, 104, 97)),
 ('root', 'CB', '64dd17', (100, 221, 23)),
 ('root', 'HDB', '36b1c0', (54, 177, 192)),
 ('root', 'Ld', '313040', (49, 48, 64)),
 ('root', 'mcer', 'dedede', (222, 222, 222)),
 ('root', 'MS', 'ffff00', (255, 255, 0)),
 ('root', 'PLd', 'c26965', (194, 105, 101)),
 ('root', 'S2', 'dfca91', (223, 202, 145)),
 ('root', 'SIB', '00bff3', (0, 191, 243)),
 ('root', 'unnamed', 'b7b29c', (183, 178, 156)),
 ('root', '3V', 'f2395b', (242, 57, 91)),
 ('root', 'A24aa', '00b0ff', (0, 176, 255)),
 ('root', 'A24bb', '7e57c2', (126, 87, 194)),
 ('root', 'AA', 'dba739', (219, 167, 57)),
 ('root', 'acp', 'cad7bb', (202, 215, 187)),
 ('root', 'AIP', '81242f', (129, 36, 47)),
 ('root', 'B', 'f8ffd9', (248, 255, 217)),
 ('root', 'BAC', 'ffab80', (255, 171, 128)),
 ('root', 'CxA1', 'c4c34d', (196, 195, 77)),
 ('root', 'CxA2', 'c44444', (196, 68, 68)),
 ('root', 'CxA3', '0c4ddd', (12, 77, 221)),
 ('root', 'DA14', 'b39ddb', (179, 157, 219)),
 ('root', 'EGP', 'b47178', (180, 113, 120)),
 ('root', 'f', '55aba8', (85, 171, 168)),
 ('root', 'ic', '651c27', (101, 28, 39)),
 ('root', 'IPACL', 'a2b600', (162, 182, 0)),
 ('root', 'IPACM', 'a2b6ad', (162, 182, 173)),
 ('root', 'LOT', 'ef5350', (239, 83, 80)),
 ('root', 'LPO', '7cc576', (124, 197, 118)),
 ('root', 'LTer', 'e6c1b8', (230, 193, 184)),
 ('root', 'MPA', 'bea881', (190, 168, 129)),
 ('root', 'MPOC', 'efa34f', (239, 163, 79)),
 ('root', 'MPOL', 'cecece', (206, 206, 206)),
 ('root', 'MPOM', '7aa8b5', (122, 168, 181)),
 ('root', 'och', '999999', (153, 153, 153)),
 ('root', 'Pe', '92180b', (146, 24, 11)),
 ('root', 'S1BF', 'cb7546', (203, 117, 70)),
 ('root', 'S1HL', 'f2854c', (242, 133, 76)),
 ('root', 'SCh', '3d9982', (61, 153, 130)),
 ('root', 'SHy', 'a286c0', (162, 134, 192)),
 ('root', 'SO', '58bbb8', (88, 187, 184)),
 ('root', 'st', 'ffedd9', (255, 237, 217)),
 ('root', 'STLI', 'fde35b', (253, 227, 91)),
 ('root', 'STLP', '00acee', (0, 172, 238)),
 ('root', 'STLV', 'ec940e', (236, 148, 14)),
 ('root', 'STMAL', 'ae5d5c', (174, 93, 92)),
 ('root', 'STMAM', '8a354c', (138, 53, 76)),
 ('root', 'TS', 'dd9c80', (221, 156, 128)),
 ('root', 'VLPO', '330f13', (51, 15, 19)),
 ('root', 'a', '8f53af', (143, 83, 175)),
 ('root', 'ACo', '4f8bbf', (79, 139, 191)),
 ('root', 'fi', 'cf5152', (207, 81, 82)),
 ('root', 'LOT1', 'df88ab', (223, 136, 171)),
 ('root', 'LOT2', '888888', (136, 136, 136)),
 ('root', 'mch', '6a1b9a', (106, 27, 154)),
 ('root', 'PDPO', 'e38748', (227, 135, 72)),
 ('root', 'PaAP', '78b4be', (120, 180, 190)),
 ('root', 'SFO', '6dabde', (109, 171, 222)),
 ('root', 'sm', '61969c', (97, 150, 156)),
 ('root', 'sox', 'be6a8b', (190, 106, 139)),
 ('root', 'StHy', 'e3d0c2', (227, 208, 194)),
 ('root', 'STMPI', '008a35', (0, 138, 53)),
 ('root', 'STMPL', 'e9bd64', (233, 189, 100)),
 ('root', 'STMPM', 'ce9d40', (206, 157, 64)),
 ('root', 'AD', '7ba276', (123, 162, 118)),
 ('root', 'AHC', '38b7ea', (56, 183, 234)),
 ('root', 'AM', 'bac3b0', (186, 195, 176)),
 ('root', 'AMV', 'e6e7df', (230, 231, 223)),
 ('root', 'ANS', 'f8ce44', (248, 206, 68)),
 ('root', 'aot', '169e49', (22, 158, 73)),
 ('root', 'ASt', 'f06292', (240, 98, 146)),
 ('root', 'AVDM', '947d53', (148, 125, 83)),
 ('root', 'AVVL', '6b6b69', (107, 107, 105)),
 ('root', 'BAOT', '497737', (73, 119, 55)),
 ('root', 'BLA', '90a24c', (144, 162, 76)),
 ('root', 'BMA', 'faf6ad', (250, 246, 173)),
 ('root', 'CeC', '95be3e', (149, 190, 62)),
 ('root', 'CeM', 'bad538', (186, 213, 56)),
 ('root', 'CM', 'fffcd7', (255, 252, 215)),
 ('root', 'cst', '9eb0b0', (158, 176, 176)),
 ('root', 'D3V', 'da557c', (218, 85, 124)),
 ('root', 'df', 'e76847', (231, 104, 71)),
 ('root', 'IAD', '9ebdb5', (158, 189, 181)),
 ('root', 'IGP', 'fbe9d1', (251, 233, 209)),
 ('root', 'LDB', '880e4f', (136, 14, 79)),
 ('root', 'MeAD', '726958', (114, 105, 88)),
 ('root', 'MoDG', '15426c', (21, 66, 108)),
 ('root', 'opt', 'e57373', (229, 115, 115)),
 ('root', 'PaMM', 'd2bdc4', (210, 189, 196)),
 ('root', 'PaMP', '927e89', (146, 126, 137)),
 ('root', 'PaV', '7b1fa2', (123, 31, 162)),
 ('root', 'PaXi', '4971b6', (73, 113, 182)),
 ('root', 'PC', 'fff176', (255, 241, 118)),
 ('root', 'PLH', 'f5f2e1', (245, 242, 225)),
 ('root', 'PT', 'ebe4ca', (235, 228, 202)),
 ('root', 'PVA', '5a4a6e', (90, 74, 110)),
 ('root', 'RCh', 'aba494', (171, 164, 148)),
 ('root', 'RChL', 'c7e5cd', (199, 229, 205)),
 ('root', 'Re', 'd5ded9', (213, 222, 217)),
 ('root', 'Rt', 'f26432', (242, 100, 50)),
 ('root', 'RtSt', 'c8df8d', (200, 223, 141)),
 ('root', 'S1Sh', 'a2dadb', (162, 218, 219)),
 ('root', 'STSL', 'c9e7e5', (201, 231, 229)),
 ('root', 'STSM', '84a6b7', (132, 166, 183)),
 ('root', 'VA', 'e6dfb1', (230, 223, 177)),
 ('root', 'VEn', '262666', (38, 38, 102)),
 ('root', 'vhc', 'fff59d', (255, 245, 157)),
 ('root', 'VLH', 'cea344', (206, 163, 68)),
 ('root', 'VRe', 'e93c8c', (233, 60, 140)),
 ('root', 'Xi', 'ced4ca', (206, 212, 202)),
 ('root', 'EA', 'ff8a80', (255, 138, 128)),
 ('root', 'A29c', '1b5e20', (27, 94, 32)),
 ('root', 'A30', 'ec407a', (236, 64, 122)),
 ('root', 'AHP', 'fceac6', (252, 234, 198)),
 ('root', 'ArcD', 'd500f9', (213, 0, 249)),
 ('root', 'ArcL', '283593', (40, 53, 147)),
 ('root', 'ArcM', '54cb00', (84, 203, 0)),
 ('root', 'BLV', 'eddec1', (237, 222, 193)),
 ('root', 'CA2', '00c3d5', (0, 195, 213)),
 ('root', 'CA3', '7e918b', (126, 145, 139)),
 ('root', 'CeL', 'f3eee8', (243, 238, 232)),
 ('root', 'dhc', 'b5b5b5', (181, 181, 181)),
 ('root', 'EP', 'ff6f00', (255, 111, 0)),
 ('root', 'GrDG', '372b39', (55, 43, 57)),
 ('root', 'IM', 'e1d8c6', (225, 216, 198)),
 ('root', 'LDVL', 'd9caab', (217, 202, 171)),
 ('root', 'MD', '866e6e', (134, 110, 110)),
 ('root', 'MeAV', '515264', (81, 82, 100)),
 ('root', 'MEE', '8d7688', (141, 118, 136)),
 ('root', 'MHb', 'e4dbee', (228, 219, 238)),
 ('root', 'mt', '56b7a4', (86, 183, 164)),
 ('root', 'PaDC', 'd3cfce', (211, 207, 206)),
 ('root', 'Rh', 'f48fb1', (244, 143, 177)),
 ('root', 'SLu', 'cabcaf', (202, 188, 175)),
 ('root', 'SOR', '1a237e', (26, 35, 126)),
 ('root', 'vlh', 'd9d969', (217, 217, 105)),
 ('root', 'VM', '282866', (40, 40, 102)),
 ('root', 'VMHSh', '3d4049', (61, 64, 73)),
 ('root', 'ZIR', 'ebcda7', (235, 205, 167)),
 ('root', 'Ang', '551e62', (85, 30, 98)),
 ('root', 'BLP', '081f65', (8, 31, 101)),
 ('root', 'CA1', '7d7491', (125, 116, 145)),
 ('root', 'DA', 'e1d9ce', (225, 217, 206)),
 ('root', 'DA13', 'f06e00', (240, 110, 0)),
 ('root', 'DMD', 'db5440', (219, 84, 64)),
 ('root', 'I\n', 'ed8f6b', (237, 143, 107)),
 ('root', 'IMD', 'ac5d9f', (172, 93, 159)),
 ('root', 'LaDL', 'fae69d', (250, 230, 157)),
 ('root', 'LDDM', 'c915bc', (201, 21, 188)),
 ('root', 'LHb', '291709', (41, 23, 9)),
 ('root', 'MDL', '721fab', (114, 31, 171)),
 ('root', 'MDM', 'e7bdbf', (231, 189, 191)),
 ('root', 'MePD', 'b9e81e', (185, 232, 30)),
 ('root', 'PeFLH', '3e3f31', (62, 63, 49)),
 ('root', 'PLCo', '3d4944', (61, 73, 68)),
 ('root', 'PoDG', '0b0a05', (11, 10, 5)),
 ('root', 'PV', 'b99a7e', (185, 154, 126)),
 ('root', 'S1Tr', 'f9ea99', (249, 234, 153)),
 ('root', 'STIA', 'f2b96c', (242, 185, 108)),
 ('root', 'SubD', '8e7555', (142, 117, 85)),
 ('root', 'SubV', 'b39e81', (179, 158, 129)),
 ('root', 'VL', 'd5ccc5', (213, 204, 197)),
 ('root', 'VMHC', 'ebeae8', (235, 234, 232)),
 ('root', 'VMHDM', '514654', (81, 70, 84)),
 ('root', 'VMHVL', '685a4f', (104, 90, 79)),
 ('root', 'VPL', 'e8dbaf', (232, 219, 175)),
 ('root', 'BMP', 'edbfb2', (237, 191, 178)),
 ('root', 'IMG', '918754', (145, 135, 84)),
 ('root', 'LaVL', '965881', (150, 88, 129)),
 ('root', 'LaVM', '302f2a', (48, 47, 42)),
 ('root', 'LMol', 'f3f5f2', (243, 245, 242)),
 ('root', 'MCLH', 'd66b75', (214, 107, 117)),
 ('root', 'MDC', 'e2d69c', (226, 214, 156)),
 ('root', 'MePV', '006064', (0, 96, 100)),
 ('root', 'ml', '823c47', (130, 60, 71)),
 ('root', 'MTu', '51695b', (81, 105, 91)),
 ('root', 'PeF', 'e3c87b', (227, 200, 123)),
 ('root', 'PLCo1', '994a43', (153, 74, 67)),
 ('root', 'PLCo2', '444444', (68, 68, 68)),
 ('root', 'PLCo3', '99aaaa', (153, 170, 170)),
 ('root', 'PMCo', '4f8000', (79, 128, 0)),
 ('root', 'Po', '92cf67', (146, 207, 103)),
 ('root', 'SubI', 'dde5bc', (221, 229, 188)),
 ('root', 'VPM', '55476b', (85, 71, 107)),
 ('root', 'ZID', 'ff5252', (255, 82, 82)),
 ('root', 'ZIV', 'c1a5be', (193, 165, 190)),
 ('root', 'AuD', 'b9d94a', (185, 217, 74)),
 ('root', 'DA11', '2962ff', (41, 98, 255)),
 ('root', 'DMC', 'c0b6ac', (192, 182, 172)),
 ('root', 'Ect', 'aa8803', (170, 136, 3)),
 ('root', 'FC', 'a7b077', (167, 176, 119)),
 ('root', 'fr', '8f95a3', (143, 149, 163)),
 ('root', 'LHbL', '57575f', (87, 87, 95)),
 ('root', 'LHbM', '575000', (87, 80, 0)),
 ('root', 'MEI', '0185f1', (1, 133, 241)),
 ('root', 'p3', '33691e', (51, 105, 30)),
 ('root', 'PHD', '142501', (20, 37, 1)),
 ('root', 'PRh', 'bf3504', (191, 53, 4)),
 ('root', 'PTe', '00d9d9', (0, 217, 217)),
 ('root', 'PVP', 'd1ccc8', (209, 204, 200)),
 ('root', 'RAPir', '8e704c', (142, 112, 76)),
 ('root', 'Sub', 'd4cdbb', (212, 205, 187)),
 ('root', 'Te', 'c0ad9c', (192, 173, 156)),
 ('root', 'AHiAL', '9a9e6c', (154, 158, 108)),
 ('root', 'Au1', '004950', (0, 73, 80)),
 ('root', 'AuV', 'ff2b7f', (255, 43, 127)),
 ('root', 'CL', 'f79cad', (247, 156, 173)),
 ('root', 'DLG', '9c9006', (156, 144, 6)),
 ('root', 'DLEnt', 'ef4423', (239, 68, 35)),
 ('root', 'DMV', 'fbf3cf', (251, 243, 207)),
 ('root', 'eml', '2e9b95', (46, 155, 149)),
 ('root', 'LPMR', '853f8a', (133, 63, 138)),
 ('root', 'LPtA', 'e1c347', (225, 195, 71)),
 ('root', 'MPtA', '91adb9', (145, 173, 185)),
 ('root', 'ns', '6e5745', (110, 87, 69)),
 ('root', 'OPC', 'ffd9d8', (255, 217, 216)),
 ('root', 'STh', 'c8af91', (200, 175, 145)),
 ('root', 'VMH', 'e0d0ac', (224, 208, 172)),
 ('root', 'ArcLP', '6e162c', (110, 22, 44)),
 ('root', 'ArcMP', 'b66079', (182, 96, 121)),
 ('root', 'InfS', 'deb156', (222, 177, 86)),
 ('root', 'LPLR', '7d7187', (125, 113, 135)),
 ('root', 'PH', '687e8c', (104, 126, 140)),
 ('root', 'PrG', '2979ff', (41, 121, 255)),
 ('root', 'scp', '588487', (88, 132, 135)),
 ('root', 'VPPC', '98667f', (152, 102, 127)),
 ('root', 'AHiPM', 'a4c639', (164, 198, 57)),
 ('root', 'APir', 'd97a36', (217, 122, 54)),
 ('root', 'APTD', '2b95d2', (43, 149, 210)),
 ('root', 'cg', '413d92', (65, 61, 146)),
 ('root', 'cp', '205cc0', (32, 92, 192)),
 ('root', 'Dk', '16a61e', (22, 166, 30)),
 ('root', 'Eth', '59a3fc', (89, 163, 252)),
 ('root', 'IGL', 'e3b79a', (227, 183, 154)),
 ('root', 'IMA', 'ece3d1', (236, 227, 209)),
 ('root', 'LM', 'ff7243', (255, 114, 67)),
 ('root', 'LPLC', 'e64d34', (230, 77, 52)),
 ('root', 'LPMC', '528036', (82, 128, 54)),
 ('root', 'LT', 'f70078', (247, 0, 120)),
 ('root', 'Lth', 'e66000', (230, 96, 0)),
 ('root', 'MCPC', '3b5998', (59, 89, 152)),
 ('root', 'MGD', '25a0ca', (37, 160, 202)),
 ('root', 'MGV', 'dd4b39', (221, 75, 57)),
 ('root', 'ML', '003580', (0, 53, 128)),
 ('root', 'MM', 'ffeb3b', (255, 235, 59)),
 ('root', 'mp', 'ea4c89', (234, 76, 137)),
 ('root', 'MPT', '89c507', (137, 197, 7)),
 ('root', 'mtg', '4e6252', (78, 98, 82)),
 ('root', 'MZMG', 'f77f00', (247, 127, 0)),
 ('root', 'OPT', 'f05e1b', (240, 94, 27)),
 ('root', 'PBP', 'ff0084', (255, 0, 132)),
 ('root', 'pc', 'dd0017', (221, 0, 23)),
 ('root', 'PCom', '82b548', (130, 181, 72)),
 ('root', 'PLi', 'fd0001', (253, 0, 1)),
 ('root', 'PPA', '4caf50', (76, 175, 80)),
 ('root', 'PtPD', 'dda35a', (221, 163, 90)),
 ('root', 'PtPR', 'dda000', (221, 160, 0)),
 ('root', 'REn', 'ffee58', (255, 238, 88)),
 ('root', 'REth', '0140ca', (1, 64, 202)),
 ('root', 'RMM', 'fc4f08', (252, 79, 8)),
 ('root', 'RPF', '171515', (23, 21, 21)),
 ('root', 'SCO', '3d9ae8', (61, 154, 232)),
 ('root', 'SNCD', '0063dc', (0, 99, 220)),
 ('root', 'SNL', '007cc3', (0, 124, 195)),
 ('root', 'SNR', '3287c1', (50, 135, 193)),
 ('root', 'SPFPC', 'ee6123', (238, 97, 35)),
 ('root', 'str', 'b4b5a3', (180, 181, 163)),
 ('root', 'Subiculum', 'e53935', (229, 57, 53)),
 ('root', 'TeA', 'eb6d20', (235, 109, 32)),
 ('root', 'V1', '0c76ab', (12, 118, 171)),
 ('root', 'V2L', 'ee4056', (238, 64, 86)),
 ('root', 'V2ML', '97b538', (151, 181, 56)),
 ('root', 'V2MM', '005cff', (0, 92, 255)),
 ('root', 'VLi', '8ba753', (139, 167, 83)),
 ('root', 'VS', '5ba525', (91, 165, 37)),
 ('root', 'VTAR', 'dd1812', (221, 24, 18)),
 ('root', 'VTM', 'f9ee30', (249, 238, 48)),
 ('root', 'ZIC', 'db7132', (219, 113, 50)),
 ('root', 'APTV', '1c1c1c', (28, 28, 28)),
 ('root', 'Aq', '003e6a', (0, 62, 106)),
 ('root', 'DS', '0085ca', (0, 133, 202)),
 ('root', 'IF', 'c3000d', (195, 0, 13)),
 ('root', 'InC', '76cc1e', (118, 204, 30)),
 ('root', 'InCSh', 'e03500', (224, 53, 0)),
 ('root', 'ipf', '0e76a8', (14, 118, 168)),
 ('root', 'MA3', '365ebf', (54, 94, 191)),
 ('root', 'MGM', '73ba37', (115, 186, 55)),
 ('root', 'MT', '6567a5', (101, 103, 165)),
 ('root', 'p1', 'e040fb', (224, 64, 251)),
 ('root', 'p1Rt', 'aa00ff', (170, 0, 255)),
 ('root', 'PIL', '558b2f', (85, 139, 47)),
 ('root', 'pIPAG', '1976d2', (25, 118, 210)),
 ('root', 'PP', '00af81', (0, 175, 129)),
 ('root', 'PrEW', 'b71c1c', (183, 28, 28)),
 ('root', 'RLi', '0096d6', (0, 150, 214)),
 ('root', 'SG', 'cf0005', (207, 0, 5)),
 ('root', 'TG', '448aff', (68, 138, 255)),
 ('root', 'InWh', '576396', (87, 99, 150)),
 ('root', 'PaC', 'd82028', (216, 32, 40)),
 ('root', 'PN', '29a0b7', (41, 160, 183)),
 ('root', 'RPC', 'a086d3', (160, 134, 211)),
 ('root', '3N', '34526f', (52, 82, 111)),
 ('root', '3PC', 'ea0a8e', (234, 10, 142)),
 ('root', 'A29b', '00e5ff', (0, 229, 255)),
 ('root', 'alv', 'ff0000', (255, 0, 0)),
 ('root', 'bas', 'ff8700', (255, 135, 0)),
 ('root', 'bic', 'ff7700', (255, 119, 0)),
 ('root', 'BIC', 'd54e21', (213, 78, 33)),
 ('root', 'CEnt', '9bc848', (155, 200, 72)),
 ('root', 'CLi', '6441a5', (100, 65, 165)),
 ('root', 'DIEnt', '5cb868', (92, 184, 104)),
 ('root', 'DLPAG', '008ace', (0, 138, 206)),
 ('root', 'DMPAG', '1e477a', (30, 71, 122)),
 ('root', 'DpG', '3b7bbf', (59, 123, 191)),
 ('root', 'EW', 'ff6600', (255, 102, 0)),
 ('root', 'ID', '720e9e', (114, 14, 158)),
 ('root', 'InG', 'ed812b', (237, 129, 43)),
 ('root', 'IPA', 'c4302b', (196, 48, 43)),
 ('root', 'IPC', '7eb400', (126, 180, 0)),
 ('root', 'IPDL', '9aca3c', (154, 202, 60)),
 ('root', 'IPI', '45668e', (69, 102, 142)),
 ('root', 'IPL', '0ba6ab', (11, 166, 171)),
 ('root', 'LPAG', '5eab1f', (94, 171, 31)),
 ('root', 'm5', '2b88d9', (43, 136, 217)),
 ('root', 'mDR', 'eeff41', (238, 255, 65)),
 ('root', 'me5', 'dd4814', (221, 72, 20)),
 ('root', 'MEnt', 'f86960', (248, 105, 96)),
 ('root', 'MiTg', 'e8e6f4', (232, 230, 244)),
 ('root', 'mlf', '0f71b4', (15, 113, 180)),
 ('root', 'MoS', '78a300', (120, 163, 0)),
 ('root', 'mRT', '40c4ff', (64, 196, 255)),
 ('root', 'Op', '76b900', (118, 185, 0)),
 ('root', 'PaS', '06afd8', (6, 175, 216)),
 ('root', 'Pn', '5498dc', (84, 152, 220)),
 ('root', 'Post', 'fee100', (254, 225, 0)),
 ('root', 'PTg', '126567', (18, 101, 103)),
 ('root', 'PrS', '00a478', (0, 164, 120)),
 ('root', 'RRF', 'ef1d1d', (239, 29, 29)),
 ('root', 'rs', '3388ff', (51, 136, 255)),
 ('root', 's5', '464646', (70, 70, 70)),
 ('root', 'xscp', 'c62828', (198, 40, 40)),
 ('root', 'Su3', 'd7584f', (215, 88, 79)),
 ('root', 'Su3C', 'f74425', (247, 68, 37)),
 ('root', 'SubB', 'ef8236', (239, 130, 54)),
 ('root', 'SuG', '183693', (24, 54, 147)),
 ('root', 'tfp', '21759b', (33, 117, 155)),
 ('root', 'ts', '5e8b1d', (94, 139, 29)),
 ('root', 'tth', '008cdd', (0, 140, 221)),
 ('root', 'V1B', 'f47a20', (244, 122, 32)),
 ('root', 'V1M', '00aff0', (0, 175, 240)),
 ('root', 'VIEnt', '256a92', (37, 106, 146)),
 ('root', 'VLPAG', '5b009c', (91, 0, 156)),
 ('root', 'VTA', 'c41200', (196, 18, 0)),
 ('root', 'Zo', 'b9070a', (185, 7, 10)),
 ('root', '4N', 'e3aacd', (227, 170, 205)),
 ('root', '4Sh', 'e3c1d9', (227, 193, 217)),
 ('root', 'DpWh', '318bff', (49, 139, 255)),
 ('root', 'ECIC', '8083a6', (128, 131, 166)),
 ('root', 'isRT', '18ffff', (24, 255, 255)),
 ('root', 'll', 'ef5160', (239, 81, 96)),
 ('root', 'mcp', '8b576e', (139, 87, 110)),
 ('root', 'PBG', '394458', (57, 68, 88)),
 ('root', 'PiSt', 'f04780', (240, 71, 128)),
 ('root', 'PMnR', 'ed174b', (237, 23, 75)),
 ('root', 'PrCnF', '9d7eb9', (157, 126, 185)),
 ('root', 'Rbd', '6f84bb', (111, 132, 187)),
 ('root', 'STr', 'e5deee', (229, 222, 238)),
 ('root', 'SuL', '303f9f', (48, 63, 159)),
 ('root', 'v', 'd1a7cd', (209, 167, 205)),
 ('root', '1Cb', '4a148c', (74, 20, 140)),
 ('root', '2Cb', 'e8c4d0', (232, 196, 208)),
 ('root', '3Cb', 'ffc46a', (255, 196, 106)),
 ('root', '4Cb', '01b37f', (1, 179, 127)),
 ('root', '4n', 'cfdda0', (207, 221, 160)),
 ('root', '4V', 'd32f2f', (211, 47, 47)),
 ('root', '5Cb', '31302e', (49, 48, 46)),
 ('root', '5Ma', '5a4939', (90, 73, 57)),
 ('root', '5Te', 'fed2b9', (254, 210, 185)),
 ('root', '5MHy', '70614e', (112, 97, 78)),
 ('root', '7n', 'c5b9a9', (197, 185, 169)),
 ('root', '8cn', '884636', (136, 70, 54)),
 ('root', 'NA5', '4b2d23', (75, 45, 35)),
 ('root', 'Bar', '207b5c', (32, 123, 92)),
 ('root', 'cbw', '36ba8b', (54, 186, 139)),
 ('root', 'CGA', 'ec9a60', (236, 154, 96)),
 ('root', 'CGB', 'b46135', (180, 97, 53)),
 ('root', 'CGO', 'efdbb8', (239, 219, 184)),
 ('root', 'Cx', 'f2e6d6', (242, 230, 214)),
 ('root', 'DMTg', '6ac17c', (106, 193, 124)),
 ('root', 'Fl', '019362', (1, 147, 98)),
 ('root', 'GrC', 'ad9e7f', (173, 158, 127)),
 ('root', 'LC', 'c7743e', (199, 116, 62)),
 ('root', 'LDTg', 'd4e59f', (212, 229, 159)),
 ('root', 'LPB', '7d2b42', (125, 43, 66)),
 ('root', 'LPBI', 'dad6b1', (218, 214, 177)),
 ('root', 'LPBV', '4e6a15', (78, 106, 21)),
 ('root', 'LSO', 'efc9a5', (239, 201, 165)),
 ('root', 'LVPO', '7e5f4d', (126, 95, 77)),
 ('root', 'Me5', '12527e', (18, 82, 126)),
 ('root', 'MPB', 'fff1e4', (255, 241, 228)),
 ('root', 'MSO', 'e2d7d3', (226, 215, 211)),
 ('root', 'MVPO', 'f26655', (242, 102, 85)),
 ('root', 'P5', '0e7ec9', (14, 126, 201)),
 ('root', 'PCGS', 'eadbbe', (234, 219, 190)),
 ('root', 'PDTg', 'f3e3c1', (243, 227, 193)),
 ('root', 'POH', 'e6c3a3', (230, 195, 163)),
 ('root', 'Pr5DM', 'f0e8e5', (240, 232, 229)),
 ('root', 'Pr5VL', '97cf90', (151, 207, 144)),
 ('root', 'py', '00b6b9', (0, 182, 185)),
 ('root', 'RtTg', '77787c', (119, 120, 124)),
 ('root', 'RtTgL', 'cd905a', (205, 144, 90)),
 ('root', 'RIP', 'c55339', (197, 83, 57)),
 ('root', 'Sim', '9a7f6c', (154, 127, 108)),
 ('root', 'Sph', 'ffead5', (255, 234, 213)),
 ('root', 'SPO', 'a1847c', (161, 132, 124)),
 ('root', 'Su5', 'ffe1a5', (255, 225, 165)),
 ('root', 'SubCD', '60c198', (96, 193, 152)),
 ('root', 'tz', 'f59b92', (245, 155, 146)),
 ('root', 'Tz', '7dc466', (125, 196, 102)),
 ('root', 'VCA', 'eee4c0', (238, 228, 192)),
 ('root', 'vsc', 'f6846a', (246, 132, 106)),
 ('root', 'IF5', '607d8b', (96, 125, 139)),
 ('root', 'RMg', 'b76057', (183, 96, 87)),
 ('root', '5ADi', '304ffe', (48, 79, 254)),
 ('root', '5Tr', 'fee2ca', (254, 226, 202)),
 ('root', 'DPO', '82c3eb', (130, 195, 235)),
 ('root', 'LR4V', 'fbbb8d', (251, 187, 141)),
 ('root', 'PFl ', '987562', (152, 117, 98)),
 ('root', 'PnV', '87524c', (135, 82, 76)),
 ('root', 'scpd', 'ffcc00', (255, 204, 0)),
 ('root', 'CG', '3d5afe', (61, 90, 254)),
 ('root', 'SimA', 'e4c4af', (228, 196, 175)),
 ('root', 'SimB', 'fee9d6', (254, 233, 214)),
 ('root', 'SuVe', '47799a', (71, 121, 154)),
 ('root', 'AC', 'c6ff00', (198, 255, 0)),
 ('root', 'ac', 'b27cda', (178, 124, 218))
 ]
"""lst=[]
for i in regs_per_section.values():
    lst=i+lst
for i in Regions_n_colors_List:
    if i[1] not in set(lst):
        print (i)"""