from regionscode.regions_per_sections_rat import regs_per_section, Regions_n_colors_List


def create_regs_n_colors_per_sec_list(atlasnum):
    regs_per_sec_List = regs_per_section[int(atlasnum)] #list
    regs_n_colors_per_sec_List = [('root', 'not detected', '000000', (0, 0, 0))]
    for elem in Regions_n_colors_List:
        if elem[-3] in regs_per_sec_List:
            regs_n_colors_per_sec_List.append(elem)
   
    Bgr_Color_List = []
    Rgb_Color_List = []
    for elem in regs_n_colors_per_sec_List:
        Rgb_Color_List.append(elem[-1])
        Bgr_Color_List.append((elem[-1][2],elem[-1][1],elem[-1][0]))

    return regs_n_colors_per_sec_List, Rgb_Color_List, Bgr_Color_List


Region_names = ['A32D _L', 'A32D _R', 'A32V _L', 'A32V _R', 'aca _L', 'aca _R', 'AID _L', 'AID _R', 'AIV _L', 'AIV _R', 'AOL _L', 'AOL _R', 'AOVP _L', 'AOVP _R', 'Cl _L', 'Cl _R', 'DEn _L', 'DEn _R', 'DTr _L', 'DTr _R', 'DTT1 _L', 'DTT1 _R', 'DTT2 _L', 'DTT2 _R', 'DTT3  _L', 'DTT3  _R', 'RMS/OV _L', 'RMS/OV _R', 'fmi _L', 'fmi _R', 'Fr3 _L', 'Fr3 _R', 'IEn _L', 'IEn _R', 'lo _L', 'lo _R', 'LO _L', 'LO _R', 'lofr _L', 'lofr _R', 'M1 _L', 'M1 _R', 'M2 _L', 'M2 _R', 'MO _L', 'MO _R', 'mofr _L', 'mofr _R', 'Pir1a _L', 'Pir1a _R', 'Pir1b _L', 'Pir1b _R', 'Pir2 _L', 'Pir2 _R', 'Pir3 _L', 'Pir3 _R', 'VO _L', 'VO _R', 'VTT1 _L', 'VTT1 _R', 'VTT2 _L', 'VTT2 _R', 'VTT3 _L', 'VTT3 _R', 'AOP _L', 'AOP _R', 'DP _L', 'DP _R', 'Pir1 _L', 'Pir1 _R', 'A25 _L', 'A25 _R', 'AcbSh _L', 'AcbSh _R', 'azac _L', 'azac _R', 'DI _L', 'DI _R', 'ICj _L', 'ICj _R', 'Nv _L', 'Nv _R', 'S1J _L', 'S1J _R', 'Tu1 _L', 'Tu1 _R', 'Tu2 _L', 'Tu2 _R', 'Tu3 _L', 'Tu3 _R', 'A24a _L', 'A24a _R', 'A24b _L', 'A24b _R', 'AcbC _L', 'AcbC _R', 'azp _L', 'azp _R', 'CPu _L', 'CPu _R', 'GI _L', 'GI _R', 'mfb _L', 'mfb _R', 'VP _L', 'VP _R', 'A33 _L', 'A33 _R', 'cc _L', 'cc _R', 'E _L', 'E _R', 'ec _L', 'ec _R', 'IG _L', 'IG _R', 'LSI _L', 'LSI _R', 'LSS _L', 'LSS _R', 'LV _L', 'LV _R', 'S1DZ _L', 'S1DZ _R', 'S1DZO _L', 'S1DZO _R', 'S1FL _L', 'S1FL _R', 'S1ULp _L', 'S1ULp _R', 'SHi _L', 'SHi _R', 'acer _L', 'acer _R', 'DCI _L', 'DCI _R', 'ICjM _L', 'ICjM _R', 'LAcbSh _L', 'LAcbSh _R', 'LSD _L', 'LSD _R', 'LSV _L', 'LSV _R', 'Tu _L', 'Tu _R', 'VCI _L', 'VCI _R', 'PDZ _L', 'PDZ _R', 'VDB _L', 'VDB _R', 'CB _L', 'CB _R', 'HDB _L', 'HDB _R', 'Ld _L', 'Ld _R', 'mcer _L', 'mcer _R', 'MS _L', 'MS _R', 'PLd _L', 'PLd _R', 'S2 _L', 'S2 _R', 'SIB _L', 'SIB _R', 'unnamed _L', 'unnamed _R', '3V _L', '3V _R', 'AA _L', 'AA _R', 'acp _L', 'acp _R', 'AIP _L', 'AIP _R', 'B _L', 'B _R', 'BAC _L', 'BAC _R', 'CxA1 _L', 'CxA1 _R', 'CxA2 _L', 'CxA2 _R', 'CxA3 _L', 'CxA3 _R', 'DA14 _L', 'DA14 _R', 'EGP _L', 'EGP _R', 'f _L', 'f _R', 'ic _L', 'ic _R', 'IPACL _L', 'IPACL _R', 'IPACM _L', 'IPACM _R', 'LOT _L', 'LOT _R', 'LPO _L', 'LPO _R', 'LTer _L', 'LTer _R', 'MPA _L', 'MPA _R', 'MPOC _L', 'MPOC _R', 'MPOL _L', 'MPOL _R', 'MPOM _L', 'MPOM _R', 'och _L', 'och _R', 'Pe _L', 'Pe _R', 'S1BF _L', 'S1BF _R', 'S1HL _L', 'S1HL _R', 'SCh _L', 'SCh _R', 'SHy _L', 'SHy _R', 'SO _L', 'SO _R', 'st _L', 'st _R', 'STLI _L', 'STLI _R', 'STLP _L', 'STLP _R', 'STLV _L', 'STLV _R', 'STMAL _L', 'STMAL _R', 'STMAM _L', 'STMAM _R', 
'TS _L', 'TS _R', 'VLPO _L', 'VLPO _R', 'a _L', 'a _R', 'ACo _L', 'ACo _R', 'fi _L', 'fi _R', 'LOT1 _L', 'LOT1 _R', 'LOT2 _L', 'LOT2 _R', 'mch _L', 'mch _R', 'PDPO _L', 'PDPO _R', 'PaAP _L', 'PaAP _R', 'SFO _L', 'SFO _R', 'sm _L', 'sm _R', 'sox _L', 'sox _R', 'StHy _L', 'StHy _R', 'STMPI _L', 'STMPI _R', 'STMPL _L', 'STMPL _R', 'STMPM _L', 'STMPM _R', 'AD _L', 'AD _R', 'AHC _L', 'AHC _R', 'AM _L', 'AM _R', 'AMV _L', 'AMV _R', 'ANS _L', 'ANS _R', 'aot _L', 'aot _R', 'ASt _L', 'ASt _R', 'AVDM _L', 'AVDM _R', 'AVVL _L', 'AVVL _R', 'BAOT _L', 'BAOT _R', 'BLA _L', 'BLA _R', 'BMA _L', 'BMA _R', 'CeC _L', 'CeC _R', 'CeM _L', 'CeM _R', 'CM _L', 'CM _R', 'cst _L', 'cst _R', 'D3V _L', 'D3V _R', 'df _L', 'df _R', 'IAD _L', 'IAD _R', 'IGP _L', 'IGP _R', 'LDB _L', 'LDB _R', 'MeAD _L', 'MeAD _R', 'MoDG _L', 'MoDG _R', 'opt _L', 'opt _R', 'PaMM _L', 'PaMM _R', 'PaMP _L', 'PaMP _R', 'PaV _L', 'PaV _R', 'PaXi _L', 'PaXi _R', 'PC _L', 'PC _R', 'PLH _L', 'PLH _R', 'PT _L', 'PT _R', 'PVA _L', 'PVA _R', 'RCh _L', 'RCh _R', 'RChL _L', 'RChL _R', 'Re _L', 'Re _R', 'Rt _L', 'Rt _R', 'RtSt _L', 'RtSt _R', 'S1Sh _L', 'S1Sh _R', 'STSL _L', 'STSL _R', 'STSM _L', 'STSM _R', 'VA _L', 'VA _R', 'VEn _L', 'VEn _R', 'vhc _L', 'vhc _R', 'VLH _L', 'VLH _R', 'VRe _L', 'VRe _R', 'Xi _L', 'Xi _R', 'EA _L', 'EA _R', 'A29c _L', 'A29c _R', 'A30 _L', 'A30 _R', 'AHP _L', 'AHP _R', 'ArcD _L', 'ArcD _R', 'ArcL _L', 'ArcL _R', 'ArcM _L', 'ArcM _R', 'BLV _L', 'BLV _R', 'CA2 _L', 'CA2 _R', 'CA3 _L', 'CA3 _R', 'CeL _L', 'CeL _R', 'dhc _L', 'dhc _R', 'EP _L', 'EP _R', 'GrDG _L', 'GrDG _R', 'IM _L', 'IM _R', 'LDVL _L', 'LDVL _R', 'MD _L', 'MD _R', 'MeAV _L', 'MeAV _R', 'MEE _L', 'MEE _R', 'MHb _L', 'MHb _R', 'mt _L', 'mt _R', 'PaDC _L', 'PaDC _R', 'Rh _L', 'Rh _R', 'SLu _L', 'SLu _R', 'SOR _L', 'SOR _R', 'vlh _L', 'vlh _R', 'VM _L', 'VM _R', 'VMHSh _L', 'VMHSh _R', 'ZIR _L', 'ZIR _R', 'Ang _L', 'Ang _R', 'BLP _L', 'BLP _R', 'CA1 _L', 'CA1 _R', 'DA _L', 'DA _R', 'DA13 _L', 'DA13 _R', 'DMD _L', 'DMD _R', 'I\n _L', 'I\n _R', 'IMD _L', 'IMD _R', 'LaDL _L', 'LaDL _R', 'LDDM _L', 'LDDM _R', 'LHb _L', 'LHb _R', 'MDL _L', 'MDL _R', 'MDM _L', 'MDM _R', 'MePD _L', 'MePD _R', 'PeFLH _L', 'PeFLH _R', 'PLCo _L', 'PLCo _R', 'PoDG _L', 'PoDG _R', 'PV _L', 'PV _R', 'S1Tr _L', 'S1Tr _R', 'STIA _L', 'STIA _R', 'SubD _L', 'SubD _R', 'SubV _L', 'SubV _R', 'VL _L', 'VL _R', 'VMHC _L', 'VMHC _R', 'VMHDM _L', 'VMHDM _R', 'VMHVL _L', 'VMHVL _R', 'VPL _L', 'VPL _R', 'BMP _L', 'BMP _R', 'IMG _L', 'IMG _R', 'LaVL _L',
'LaVL _R', 'LaVM _L', 'LaVM _R', 'LMol _L', 'LMol _R', 'MCLH _L', 'MCLH _R', 'MDC _L', 'MDC _R', 'MePV _L', 'MePV _R', 'ml _L', 'ml _R', 'MTu _L', 'MTu _R', 'PeF _L', 'PeF _R', 'PLCo1 _L', 'PLCo1 _R', 'PLCo2 _L', 'PLCo2 _R', 'PLCo3 _L', 'PLCo3 _R', 'PMCo _L', 'PMCo _R', 'Po _L', 'Po _R', 'SubI _L', 'SubI _R', 'VPM _L', 'VPM _R', 'ZID _L', 'ZID _R', 'ZIV _L', 'ZIV _R', 'AuD _L', 'AuD _R', 'DA11 _L', 'DA11 _R', 'DMC _L', 'DMC _R', 'Ect _L', 'Ect _R', 'FC _L', 'FC _R', 'fr _L', 'fr _R', 'LHbL _L', 'LHbL _R', 'LHbM _L', 'LHbM _R', 'MEI _L', 'MEI _R', 'p3 _L', 'p3 _R', 'PHD _L', 'PHD _R', 'PRh _L', 'PRh _R', 'PTe _L', 'PTe _R', 'PVP _L', 'PVP _R', 'RAPir _L', 'RAPir _R', 'Sub _L', 'Sub _R', 'Te _L', 'Te _R', 'AHiAL _L', 'AHiAL _R', 'Au1 _L', 'Au1 _R', 'AuV _L', 'AuV _R', 'CL _L', 'CL _R', 'DLG _L', 'DLG _R', 'DLEnt _L', 'DLEnt _R', 'DMV _L', 'DMV _R', 'eml _L', 'eml _R', 'LPMR _L', 'LPMR _R', 'LPtA _L', 'LPtA _R', 'MPtA _L', 'MPtA _R', 'ns _L', 'ns _R', 'OPC _L', 'OPC _R', 'STh _L', 'STh _R', 'VMH _L', 'VMH _R', 'ArcLP _L', 'ArcLP _R', 'ArcMP _L', 'ArcMP _R', 'InfS _L', 'InfS _R', 'LPLR _L', 'LPLR _R', 'PH _L', 'PH _R', 'PrG _L', 'PrG _R', 'scp _L', 'scp _R', 'VPPC _L', 'VPPC _R', 'AHiPM _L', 'AHiPM _R', 'APir _L', 'APir _R', 'APTD _L', 'APTD _R', 'cg _L', 'cg _R', 'cp _L', 'cp _R', 'Dk _L', 'Dk _R', 'Eth _L', 'Eth _R', 'IGL _L', 'IGL _R', 'IMA _L', 'IMA _R', 'LM _L', 'LM _R', 'LPLC _L', 'LPLC _R', 'LPMC _L', 'LPMC _R', 'LT _L', 'LT _R', 'Lth _L', 'Lth _R', 'MCPC _L', 'MCPC _R', 'MGD _L', 'MGD _R', 'MGV _L', 'MGV _R', 'ML _L', 'ML _R', 'MM _L', 'MM _R', 'mp _L', 'mp _R', 'MPT _L', 'MPT _R', 'mtg _L', 'mtg _R', 'MZMG _L', 'MZMG _R', 'OPT _L', 'OPT _R', 'PBP _L', 'PBP _R', 'pc _L', 'pc _R', 'PCom _L', 'PCom _R', 'PLi _L', 'PLi _R', 'PPA _L', 'PPA _R', 'PtPD _L', 'PtPD _R', 'PtPR _L', 'PtPR _R', 'REn _L', 'REn _R', 'REth _L', 'REth _R', 'RMM _L', 'RMM _R', 'RPF _L', 'RPF _R', 'SCO _L', 'SCO _R', 'SNCD _L', 'SNCD _R', 'SNL _L', 'SNL _R', 'SNR _L', 'SNR _R', 'SPFPC _L', 'SPFPC _R', 'str _L', 'str _R', 'Subiculum _L', 'Subiculum _R', 'TeA _L', 'TeA _R', 'V1 _L', 'V1 _R', 'V2L _L', 'V2L _R', 'V2ML _L', 'V2ML _R', 'V2MM _L', 'V2MM _R', 'VLi _L', 'VLi _R', 'VS _L', 'VS _R', 'VTAR _L', 'VTAR _R', 'VTM _L', 'VTM _R', 'ZIC _L', 'ZIC _R', 'APTV _L', 'APTV _R', 'Aq _L', 'Aq _R', 'DS _L', 'DS _R', 'IF _L', 'IF _R', 'InC _L', 'InC _R', 'InCSh _L', 'InCSh _R', 'ipf _L', 'ipf _R', 'MA3 _L', 'MA3 _R', 'MGM _L', 'MGM _R', 'MT _L', 'MT _R', 'p1 _L', 'p1 _R', 
'p1Rt _L', 'p1Rt _R', 'PIL _L', 'PIL _R', 'pIPAG _L', 'pIPAG _R', 'PP _L', 'PP _R', 'PrEW _L', 'PrEW _R', 'RLi _L', 'RLi _R', 'SG _L', 'SG _R', 'TG _L', 'TG _R', 'InWh _L', 'InWh _R', 'PaC _L', 'PaC _R', 'PN _L', 'PN _R', 'RPC _L', 'RPC _R', '3N _L', '3N _R', '3PC _L', '3PC _R', 'A29b _L', 'A29b _R', 'alv _L', 'alv _R', 'bas _L', 'bas _R', 'bic _L', 'bic _R', 'BIC _L', 'BIC _R', 'CEnt _L', 'CEnt _R', 'CLi _L', 'CLi _R', 'DIEnt _L', 'DIEnt _R', 'DLPAG _L', 'DLPAG _R', 'DMPAG _L', 'DMPAG _R', 'DpG _L', 'DpG _R', 'EW _L', 'EW _R', 'ID _L', 'ID _R', 'InG _L', 'InG _R', 'IPA _L', 'IPA _R', 'IPC _L', 'IPC _R', 'IPDL _L', 'IPDL _R', 'IPI _L', 'IPI _R', 'IPL _L', 'IPL _R', 'LPAG _L', 'LPAG _R', 'm5 _L', 'm5 _R', 'mDR _L', 'mDR _R', 'me5 _L', 'me5 _R', 'MEnt _L', 'MEnt _R', 'MiTg _L', 'MiTg _R', 'mlf _L', 'mlf _R', 'MoS _L', 'MoS _R', 'mRT _L', 'mRT _R', 'Op _L', 'Op _R', 'PaS _L', 'PaS _R', 'Pn _L', 'Pn _R', 'Post _L', 'Post _R', 'PTg _L', 'PTg _R', 'PrS _L', 'PrS _R', 'RRF _L', 'RRF _R', 'rs _L', 'rs _R', 's5 _L', 's5 _R', 'xscp _L', 'xscp _R', 'Su3 _L', 'Su3 _R', 'Su3C _L', 'Su3C _R', 'SubB _L', 'SubB _R', 'SuG _L', 'SuG _R', 'tfp _L', 'tfp _R', 'ts _L', 'ts _R', 'tth _L', 'tth _R', 'V1B _L', 'V1B _R', 'V1M _L', 'V1M _R', 'VIEnt _L', 'VIEnt _R', 'VLPAG _L', 'VLPAG _R', 'VTA _L', 'VTA _R', 'Zo _L', 'Zo _R', '4N _L', '4N _R', '4Sh _L', '4Sh _R', 'DpWh _L', 'DpWh _R', 'ECIC _L', 'ECIC _R', 'isRT _L', 'isRT _R', 'll _L', 'll _R', 'mcp _L', 'mcp _R', 'PBG _L', 'PBG _R', 'PiSt _L', 'PiSt _R', 'PMnR _L', 'PMnR _R', 'PrCnF _L', 'PrCnF _R', 'Rbd _L', 'Rbd _R', 'STr _L', 'STr _R', 'SuL _L', 'SuL _R', 'v _L', 'v _R', '1Cb _L', '1Cb _R', '2Cb _L', '2Cb _R', '3Cb _L', '3Cb _R', '4Cb _L', '4Cb _R', '4n _L', '4n _R', '4V _L', '4V _R', '5Cb _L', '5Cb _R', '5Ma _L', '5Ma _R', '5Te _L', '5Te _R', '5MHy _L', '5MHy _R', '7n _L', '7n _R', '8cn _L', '8cn _R', 'NA5 _L', 'NA5 _R', 'Bar _L', 'Bar _R', 'cbw _L', 'cbw _R', 'CGA _L', 'CGA _R', 'CGB _L', 'CGB _R', 'CGO _L', 'CGO _R', 'Cx _L', 'Cx _R', 'DMTg _L', 'DMTg _R', 'Fl _L', 'Fl _R', 'GrC _L', 'GrC _R', 'LC _L', 'LC _R', 'LDTg _L', 'LDTg _R', 'LPB _L', 'LPB _R', 'LPBI _L', 'LPBI _R', 'LPBV _L', 'LPBV _R', 'LSO _L', 'LSO _R', 'LVPO _L', 'LVPO _R', 'Me5 _L', 'Me5 _R', 'MPB _L', 'MPB _R', 'MSO _L', 'MSO _R', 'MVPO _L', 'MVPO _R', 'P5 _L', 'P5 _R', 'PCGS _L', 'PCGS _R', 'PDTg _L', 'PDTg _R', 'POH _L', 'POH _R', 'Pr5DM _L', 'Pr5DM _R', 'Pr5VL _L', 'Pr5VL _R', 'py _L', 'py _R', 'RtTg _L', 'RtTg _R', 'RtTgL _L', 'RtTgL _R', 
'A24aa _L', 'A24aa _R', 'A24bb _L', 'A24bb _R', 'RIP _L', 'RIP _R', 'Sim _L', 'Sim _R', 'Sph _L', 'Sph _R', 'SPO _L', 'SPO _R', 'Su5 _L', 'Su5 _R', 'SubCD _L', 'SubCD _R', 'tz _L', 'tz _R', 'Tz _L', 'Tz _R', 'VCA _L', 'VCA _R', 'vsc _L', 'vsc _R', 'IF5 _L', 'IF5 _R', 'RMg _L', 'RMg _R', '5ADi _L', '5ADi _R', '5Tr _L', '5Tr _R', 'DPO _L', 'DPO _R', 'LR4V _L', 'LR4V _R', 'PFl  _L', 'PFl  _R', 'PnV _L', 'PnV _R', 'scpd _L', 'scpd _R', 'CG _L', 'CG _R', 'SimA _L', 'SimA _R', 'SimB _L', 'SimB _R', 'SuVe _L', 'SuVe _R', 'AC _L', 'AC _R', 'ac _L', 'ac _R']

general_Region_names = Region_names

print(Region_names[2])